### ISSUE TITLE
Menu items 403 error

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#10293]
#### Steps to reproduce the issue

Have an error now on menu.
Maybe related to latest changes.

1. Logout
2. Login and go to Menus -> Manage
3. Now click in the sidebar "Menu items"

Or

just try to go to `/administrator/index.php?option=com_menus&view=items&menutype=`

#### Expected result

List all menu items

#### Actual result

An error has occurred.
 403 You are not authorised to view this resource.

#### System information (as much as possible)

latest staging

#### Additional comments

Probably related:
- https://github.com/joomla/joomla-cms/pull/10281
- https://github.com/joomla/joomla-cms/pull/9814

@infograf768 @bembelimen

**Comment by MATsxm** [comment]
able to reproduce - confirm<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10293">issues.joomla.org/joomla-cms/10293</a>.</sub>

**Comment by infograf768** [comment]
The link obtained from the Menu Items submenu is corrected after applying https://github.com/joomla/joomla-cms/pull/10281:

ROOT/administrator/index.php?option=com_menus&view=items&menutype=*

**Comment by andrepereiradasilva** [comment]
appled https://github.com/joomla/joomla-cms/pull/10281 and still the same problem.

**Comment by andrepereiradasilva** [comment]
@brianteeman can be close i made a PR https://github.com/joomla/joomla-cms/pull/10314

please test.
