### ISSUE TITLE
com_finder does not mark findings when word contains diacritical characters

### ISSUE THREAD

**Issue by ChrisHoefliger** [joomla/joomla-cms#10874]
#### Steps to reproduce the issue

Write an article that contains words with diacritical (non-English) characters, e.g. verhüten, Königsweg, überschauen, Hintertür
#### Expected result

Entering one of these words into the searchbox will find the words and display them in the context as expected, however they get not marked as search results as 'normal' words would.
#### Actual result

Article displayed in context, without found word marked.
#### System information (as much as possible)

Joomla 3.5.1, Apache, PHP 7.0.0, MySQL 5.5.49 on MAMP for Windows

**Comment by infograf768** [comment]
you mean that they are not highlighted?

**Comment by ChrisHoefliger** [comment]
That's what I meand, the words don't get highlighted.

**Comment by infograf768** [comment]
@chrisdavenport 
Can you look at this?

**Comment by chrisdavenport** [comment]
Confirmed.

The ?highlight argument is not correctly encoding the multibyte characters.  This can be fixed by using an optional 2nd argument to json_encode so components/com_finder/views/search/tmpl/default_result.php line 45 becomes:

`$route .= '&highlight=' . base64_encode(json_encode($this->query->highlight, JSON_UNESCAPED_UNICODE));`

Unfortunately, JSON_UNESCAPED_UNICODE is only available from PHP 5.4 onwards so you'll need to jump through some hoops if you want to fix the problem in PHP 5.3 too.

However, even with the above fix, the highlighter still doesn't work.  I'm guessing that highlight.js doesn't support UTF-8 characters properly.  You'll need a JavaScript expert to fix that one!

I'm very short of time at the moment, so I don't think I can take it much further right now.  Hopefully, someone can run with it.

**Comment by franz-wohlkoenig** [comment]
looks similar to #13498

**Comment by franz-wohlkoenig** [comment]
@ChrisHoefliger is this Issue resolved by #13498?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10874">issues.joomla.org/tracker/joomla-cms/10874</a>.</sub>

**Comment by ChrisHoefliger** [comment]
@franz-wohlkoenig Just tested in J! 3.7 Beta 4. It's not being resolved, sitauation still the same. Words without Umlauts get highlighted, words with Umlauts will be found, but no highlighting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10874">issues.joomla.org/tracker/joomla-cms/10874</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
thanks @ChrisHoefliger set Status on "Needs Review" on Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10874">issues.joomla.org/tracker/joomla-cms/10874</a>.</sub>

**Comment by Quy** [comment]
It appears to be fixed as of v3.8.4-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10874">issues.joomla.org/tracker/joomla-cms/10874</a>.</sub>
