### ISSUE TITLE
370: REGRESSION: ERROR when installing languages

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#11682]
Download https://github.com/joomla/joomla-cms/archive/3.7.x.zip
Install. Choose Extra Steps: Install Languages.
It just does not work, the page is reloaded.
[20-Aug-2016 09:05:55 UTC] PHP Notice:  Trying to get property of non-object in ROOT/installation/model/languages.php on line 234

If I still click Next without languages being install, I get an invalid token
`The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.`

this corresponds to
`$package_url = trim($update->get('downloadurl', false)->_data);`

Exchanging the file from the one in staging (3.6.3-dev) where installing works OK has no effect.

Then I tested skipping installing languages and went own installing.
I tried to install languages from Extensions->InstallLanguages
I got a message:
```
The installer can't get the URL to the remote French language. Try again later or contact the language team coordinator
The installer can't get the URL to the remote Italian language. Try again later or contact the language team coordinator
```
This for the same languages I installed correctly using staging.

**Comment by infograf768** [comment]
Is this due to the xml?
```xml
<update><name>German DE</name><description>German DE Translation of Joomla!</description><element>pkg_de-DE</element><type>package</type><version>3.6.2.1</version><downloads><downloadurl type="full" format="zip">http://joomlacode.org/gf/download/frsrelease/20359/163385/de-DE_joomla_lang_full_3.6.2v1.zip</downloadurl></downloads><targetplatform name="joomla" version="3.[0123456]"/></update>
```
i.e.
`<targetplatform name="joomla" version="3.[0123456]"/>`

**Comment by andrepereiradasilva** [comment]
it seems so

**Comment by infograf768** [comment]
time to update that if we want to work on 3.7.0 :)

**Comment by infograf768** [comment]
changing version indeed solves the issue

**Comment by zero-24** [comment]
@infograf768 can you close the issue than?

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11682">issues.joomla.org/joomla-cms/11682</a>

**Comment by zero-24** [comment]
closing as it is fixed upstream.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11682">issues.joomla.org/joomla-cms/11682</a>.</sub>

**Comment by infograf768** [comment]
Well, the value is set by the cron job.
Therefore the issue still exists for 3.7.0
PLT has to change the cron
I reopen

**Comment by infograf768** [comment]
Issues.joomla.org does not let me reopen...

**Comment by zero-24** [comment]
Set to "open" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11682">issues.joomla.org/joomla-cms/11682</a>

**Comment by zero-24** [comment]
Sorry i missunderstand you @infograf768 did you ping the PLT?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11682">issues.joomla.org/joomla-cms/11682</a>.</sub>

**Comment by infograf768** [comment]
I posted on maintainers chat

**Comment by zero-24** [comment]
:+1:

**Comment by wilsonge** [comment]
Cron job updated
