### ISSUE TITLE
Filtering by Title in list view with no matches returns COM_CONTENT_NO_ARTICLES

### ISSUE THREAD

**Issue by thoni56** [joomla/joomla-cms#12075]
### Steps to reproduce the issue
Create a menu entry with a list view for a category. Enable "filter by title". Go to the menu and enter a title which does not match anything.

### Expected result
A message saying "there are no articles in this category matching your filter" and the "filter by title" input field is shown so that you can alter the filter.

### Actual result
The message COM_CONTENT_NO_ARTICLES is shown which is something along the lines of "there are no articles in this category.", which is not a good error message for "there are no articles in this category matching your filter".

Furthermore, and worse, the "filter by title" disappears so you cannot change the filter without reloading the page.

### System information (as much as possible)
Joomla 3.6.2

**Comment by brianteeman** [comment]
I can not replicate this problem. It sounds to me that you are missing a language file

**Comment by brianteeman** [comment]
> Furthermore, and worse, the "filter by title" disappears so you cannot change the filter without reloading the page.

This is a valid issue and has already been fixed for 3.6.3

**Comment by thoni56** [comment]
Excellent!

**Comment by zero-24** [comment]
So we can close here as it is fixed with 3.6.3-dev?

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12075">issues.joomla.org/joomla-cms/12075</a>.</sub>

**Comment by wnkkm** [comment]
_the "filter by title" disappears so you cannot change the filter without reloading the page._

I still have this issue. I am using 3.7.5 now, but it happened with previous versions as well.
I had to close web browser and reopen it to remove the title filter.
How can I fix the issue?

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12075">issues.joomla.org/tracker/joomla-cms/12075</a>.</sub>

**Comment by ghost** [comment]
@wnkkm Please ask help on the [forums](https://forum.joomla.org/) as comment on closed Issue wouldn't get much Notice.
