### ISSUE TITLE
Category Links are Broken with New Routing

### ISSUE THREAD

**Issue by Chraneco** [joomla/joomla-cms#13101]
While trying to implement the new routing for JoomGallery I detected this problem:
### Steps to reproduce the issue
1. Set up a site with the "Blog" sample data.
2. Create a new content menu item of type "List All Categories" and with "Root" as the category selection.
3. When clicking on that menu item you get to a page with two links ("Uncategorised" and "Blog").
4. Verify that both links work as expected.
5. Turn on the new routing for the content component.
6. Click again on the created menu item.
7. The link for "Uncategorised" is now broken as it simple references the current page you are on.
### Expected result

All links should still work as before
### Actual result

Links from the "categories" view are broken.
### System information (as much as possible)

Tested with latest code from the 3.7.x branch.
### Additional Comments

The "Blog" link still works because it is also the default menu item, I think if more categories were listed on that page all those links would be broken.

I reported this issue before but it was mistakenly closed:
https://github.com/joomla/joomla-cms/issues/11637
Please follow the steps to reproduce exactly, this issue is still happening with the latest code.

**Comment by Bakual** [comment]
@Hackwar Can you have a look here?

**Comment by infograf768** [comment]
I confirm the issue.

**Comment by MrMusic** [comment]
I confirm the issue too.
Tested with Joomla! 3.7.0 beta1

**Comment by Hackwar** [comment]
Can you please test this on the latest staging again? We fixed a major bug about a month ago that should solve this one.

**Comment by MrMusic** [comment]
I maked a new test with the 3.7.0 staging branch from 04.03.2017.
For me the issue still exist.

**Comment by Hackwar** [comment]
Yes, I'm sorry, your issue was not solved. That should be solved by #14322 Can you please test with that patch?

**Comment by MrMusic** [comment]
>...That should be solved by #14322

Thank you! For me it looks good. :smile:
@Chraneco: Can you confirm this fix?

**Comment by Chraneco** [comment]
Yes, I can confirm that, thanks!
