### ISSUE TITLE
[com_fields] Gallery Field -> Don't work, if the "Directory" option is empty

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-cms#13744]
### Steps to reproduce the issue
Install a fresh Joomla 3.7 Alpha.
Then go to Joomla Backend -> Content -> Fields -> New -> Type: Gallery -> Save & Close
Then go to an article and try to use this new field.
The first problem is, that you can see every folder, inside the Joomla root folder
The second problem is, that the Gallery don't work.
The error message is this:
`JFolder: :files: Path is not a folder. Path: /home/web42bny2/html/37/images/images/sampledata/parks/animals`
but i choosed within the Joomla Backend this folder:
`images/sampledata/parks/animals`
If you set within the Gallery Field the Option "Directory" to "images", then everything works as excepted

### System information (as much as possible)
Joomla 3.7 Alpha 2 without Extensions
PHP 7.0.9
DB: Maria DB

**Comment by Bakual** [comment]
For the error message, see https://github.com/joomla/joomla-cms/pull/13726. I think that should solve it.

**Comment by ufuk-avcu** [comment]
I apply this via Joomla Patch Tester over the Joomla 3.7 Alpha2 and the problem is not solved.

**Comment by laoneo** [comment]
Can you test #13761 that not all subfolders are shown? Are you working on widows? Because I couldn't reproduce the issue.

**Comment by ufuk-avcu** [comment]
I tested this again, with the latest Staging from today on a LAMP enviroment and it works like excepted.
