### ISSUE TITLE
[com_fields] image list field does not show svg

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#14356]
### Steps to reproduce the issue
Setup the Media Manager Options to Allow svg, add svg suffix and Mimetype.
Upload the svg Files.

![image](https://cloud.githubusercontent.com/assets/828371/23586933/e7d2722a-01a0-11e7-9834-2b8cb9edfe50.png)

Set up an imagelist Field with the directory you uploaded the svg to.
The svgs are not displayed.

![image](https://cloud.githubusercontent.com/assets/828371/23586939/17a134be-01a1-11e7-8e1d-f582223c037c.png)

Edit: Same for Media-Field should i create a seperate issue for that?

**Comment by dgt41** [comment]
You need to go to media manager options and manually add the svg type. It is not in the lists for security reason

**Comment by coolcat-creations** [comment]
I did, as said in the description of the issue. As you see in the first screenshot they are displayed in the Mediamanager itself...

**Comment by Bakual** [comment]
> Same for Media-Field should i create a seperate issue for that?

It's the same issue if it exists.

**Comment by laoneo** [comment]
To allow only images is hard coded in the field itself https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/imagelist.php#L40. Don't know if we should break up that filter and use the media manager setting instead.

**Comment by coolcat-creations** [comment]
I think we should always use existing settings, also ACL is based on MM...

**Comment by laoneo** [comment]
The things is that the form field doesn't have any dependency to the media manager and also should not have. What we can do is to make this value as a parameter of the field itself.

**Comment by coolcat-creations** [comment]
So  it´s not dependant of the ACL of the Extension the field is using?

**Comment by laoneo** [comment]
No, actually it is hardcoded. But we can make it configurable and then set it in custom fields from the media manager. I'm talking about this setting here 
![image](https://cloud.githubusercontent.com/assets/251072/23659915/0b34736e-0348-11e7-9d43-17bc75a07bb7.png)

**Comment by coolcat-creations** [comment]
yes that would be very helpful, thank you!

**Comment by franz-wohlkoenig** [comment]
reminder @laoneo for <a href="https://issues.joomla.org/tracker/joomla-cms/14356#event-247166">comment</a><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14356">issues.joomla.org/tracker/joomla-cms/14356</a>.</sub>

**Comment by laoneo** [comment]
Is it somehow possible to assign that issue to me. Actually I don't have time to fix it, but it is no release blocker, so we can do it also in a later release.

**Comment by franz-wohlkoenig** [comment]
can you give a 3.8-Milestone so it don't get lost?

**Comment by laoneo** [comment]
3.8 should be only router but I guess I can do it in 3.7.1 or so

**Comment by franz-wohlkoenig** [comment]
added Build 3.7.1 in Issue Tracker.

**Comment by mbabker** [comment]
Build on the tracker should be the version the issue was reported against, not a projected version where an issue is fixed.

**Comment by franz-wohlkoenig** [comment]
set on "staging". 

@laoneo don't know if / how to assign it to you – @mbabker? Can set "related to Issue" if this helps.

**Comment by mbabker** [comment]
1) You can't do assignments through the tracker, we aren't wired up to work with the assignees field on GitHub

2) Assignees on GitHub is only team members with access to a repository, so even if we had that integration you can't assign this to Allon because he's not in a team with access to this repo

**Comment by franz-wohlkoenig** [comment]
thnaks for Info @mbabker

**Comment by N6REJ** [comment]
@laoneo you might find this useful https://github.com/darylldoyle/svg-sanitizer

**Comment by dgrammatiko** [comment]
@N6REJ yep: https://github.com/joomla/joomla-cms/pull/13499

**Comment by N6REJ** [comment]
@dgt41 webp is amazing!  You need to think about when to use it on which image but MAN DOES IT MAKE A HUGE DIFFERENCE.

**Comment by wilsonge** [comment]
I'm going to close this as a more specific example of #14356

**Comment by coolcat-creations** [comment]
So now both are closed?

**Comment by wilsonge** [comment]
Sorry I linked to this issue by mistake. I meant to link to https://github.com/joomla/joomla-cms/issues/16795

**Comment by coolcat-creations** [comment]
But #16795 is about the media manger. this ist about com_fields - and those have independant settings like @laoneo states above.

**Comment by mbabker** [comment]
It is the same root problem at the end of the day.

**Comment by coolcat-creations** [comment]
So we close all the issues regarding this and leave none open?

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/issues/16795 is still open and will not be closed

**Comment by coolcat-creations** [comment]
#16795 does not show the same issue.It's regarding existing images that are already uploaded and not shown. #16795 is an issue about uploading.

**Comment by hendrikbehncke** [comment]
I'd really like to open this issue again. Like explained already, issue #16795 is not related to this here.
In this issue here it is about the media field that does not allow to pick svg image files that are already uploaded and available on the server. The filter what is considered to be an image file is hard coded to the media field in https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/imagelist.php#L40
The Media Manager in Joomla already allows to upload svg image files and if uploaded it does also show these files. Why not allow these files to be picked in the form media field?

**Comment by sokoloff-rv** [comment]
When you select an image through a field with the type "media", SVG format files are not displayed. Will this be fixed in the future?

**Comment by SemaphoreOxalis** [comment]
Hi, still no option there or we miss something ? I know this Issue is closed, but can't understand why.
 
The 3.10 code still show $this->filter = '\.png$|\.gif$|\.jpg$|\.bmp$|\.ico$|\.jpeg$|\.psd$|\.eps$'; for the /libraries/joomla/form/fields/imagelist.php file. Maybe with a filter fields for better control on the permited extentions ?
