### ISSUE TITLE
[4.0] 500 when loading com_associations

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#15329]
### Steps to reproduce the issue
Multilingual site (Install languages via package install). 2 languages is enough.

Create items in both languages.
Go to `administrator/index.php?option=com_associations&view=associations`

Choose item and language
> 500 - An error has occurred.

> 'joomla40.a.alias' isn't in GROUP BY 'joomla40.a.alias' isn't in GROUP BY

**Comment by franz-wohlkoenig** [comment]
Issue confirmed.
### System information
Joomla! 4.0.0-dev (nightly Build)
macOS Sierra, 10.12.4
Firefox 52 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/327eee1baa72cb04189fe583fe80d9d40b49c3f9

@alikon does this need to be backported to staging for postgres?

**Comment by infograf768** [comment]
@wilsonge
You missed menutype line  311

Add after 
```
		if (!empty($fields['menutype']))
		{
			$query->select($db->qn($fields['menutype'], 'menutype'));
```
this
`$groupby[] = 'menutype';`

**Comment by alikon** [comment]
@wilsonge is not necessary in staging with postgresql  it works well

**Comment by wilsonge** [comment]
Fixed JM :)
