### ISSUE TITLE
3.7.2 No SEO URL Menu Navigation Issue, again

### ISSUE THREAD

**Issue by ukphotoguy** [joomla/joomla-cms#16254]
### Steps to reproduce the issue
Using a basic Joomla site with no SEO optimized URL and navigate to say a blog article layout. 

### Expected result
Normal blog layout with page tile from menu

### Actual result
The Page title will not appear but the page will be titled Articles. 

### System information (as much as possible)
expected page URL /index.php?option=com_content&view=category&layout=blog&id=10&Itemid=131
actual failed page URL /index.php?option=com_content&amp;view=category&amp;layout=blog&amp;id=12&amp;Itemid=163
There is an extra pair of & a m p in the bad URL that gets lost in this editor

### Additional comments
the "&amp;" in the URL seems to be the problem. This was the case with the last update and there was a closed tracking issue with some hacked code and the note to wait till the next update. But the issue is still therr for me. I backed out to 3.7.0 and page titles reeturned.

**Comment by ukphotoguy** [comment]
![screen shot 2017-05-24 at 21 56 23](https://issues.joomla.org/uploads/1/e94014131113707fed0bcbea1fe4499e.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16254">issues.joomla.org/tracker/joomla-cms/16254</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Can't confirm. 

On a Site with "Search Engine Friendly URLs" to "No", using a Blog-Menu the "Browser Page Title" shows "Menu Title" (also if a Value is set in "Browser Page Title").
### System information
3.7.3-dev
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by ukphotoguy** [comment]
Retested using basic protostar template and get similar results. I can PM the test URL but don't want to make it public.
The results are a little difefrnt but same issue.
Basic simple site, all joomla articles. Main Cat is Clients with three sub cat. On main cat blog page the sub-cat are displayed see cat image. If a sub-cat title is clicked that sub cat page opens with a correct page heading default from the menu title. See the using-cat-lik image. If I use the sub-cat menu link I get the page without any page title see using menu link image. 
Now I did some more looking. I have the case where no cat title is the default and no cat or page title set on the main cat clients, but I do enable page title in teh sub cat menu settings. **If I enable cat title as a global both page links work with titles.**![screen shot 2017-05-25 at 14 51 54](https://issues.joomla.org/uploads/1/f72c95560c493340b497dff6f5a1cb5d.jpg) Looks like me wanting them only on the sub-cat is my issue.![screen shot 2017-05-25 at 14 51 56](https://issues.joomla.org/uploads/1/515bf96d3424ec883f88249aa0e96913.jpg)![screen shot 2017-05-25 at 14 51 57](https://issues.joomla.org/uploads/1/f5158d96e43c0670878f906ca35047e8.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16254">issues.joomla.org/tracker/joomla-cms/16254</a>.</sub>

**Comment by PhilETaylor** [comment]
This was fixed in Joomla 3.7.2 !

**Comment by ukphotoguy** [comment]
That's what I thought so I waited for it, but it did not fix this issue so I had to back out again and raised this thread.

**Comment by andrepereiradasilva** [comment]
can't reproduce on latest staging - SEF disabled works fine

@ukphotoguy Please explain step by step how to reproduce the issue you are having in latest joomla staging so we can reproduce it.

**Comment by brianteeman** [comment]
It has been several months since this issue was created without confirmation of the issue. I am closing it at this time but it can always be reopened
