### ISSUE TITLE
[3.7.3 RC] Featured Blog shows 404 because of pagebreak plugin

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#16858]
### Steps to reproduce the issue
It seems that is has to do with the Change in https://github.com/joomla/joomla-cms/pull/11217

I tested local on a customer page and got a 404 on the Home Item (Featured Articles)
I could not reproduce the issue on a clean install, but disabling the pagebreak plugin showed the page like expected.

Seems something in the check is wrong
`	if (StringHelper::strpos($row->text, 'class="system-pagebreak') === false)
		{
			if ($page > 0)
			{
				throw new Exception(JText::_('JERROR_PAGE_NOT_FOUND'), 404);
			}
			return true;
		}`

**Comment by rdeutz** [comment]
Without instructions how to reproduce it, we can't do so much. The test seems not wrong.

**Comment by zero-24** [comment]
@coolcat-creations it has nothing todo with featured articles can you confirm that on that page a news flash module is published?

@rdeutz here is how to reproduce:

### How to reproduce

- install 3.7.3-dev
- set up a `news flash` module to the category `Joomla!` (using sample data)

### result

![image](https://user-images.githubusercontent.com/2596554/27517141-7afb456c-59c7-11e7-8368-9d3fe2bf2643.png)

Looks like some other things are broken now too.

### Reason

https://github.com/joomla/joomla-cms/blob/3.7.3-rc1/modules/mod_articles_news/helper.php#L124

Because $page is set to `1` and no page break is included this throws the error. But i don't know what the $page var is supposed to do?

Disableling the pagebreak plugin fixes the issue. To me this is a release-blocker as it breaks existing sites.

**Comment by coolcat-creations** [comment]
Thank you @zero-24 yes i confirm that unpublishing Newsflash also solves the 404 Error.

**Comment by zero-24** [comment]
@Bakual @laoneo can you take a look here and told us why you set `$page === 1` in that module?

https://github.com/joomla/joomla-cms/commit/aa862e8c694fd2be7833e16c7306c92d6409b989
https://github.com/joomla/joomla-cms/commit/2d82f4cc2d2577aa42e1e2cbd85c96cb083010c3

**Comment by rdeutz** [comment]
I don't think we need to set $page, I made a patch #16866

**Comment by laoneo** [comment]
I guess because it was set with page 1 on the other events, like onContentAfterTitle, which existed already.

**Comment by zero-24** [comment]
Closing as the PR #16866 fixes it. Thanks!

**Comment by eriknzzz** [comment]
I am new to github, but have a problem with pagebreak since Joomla 3.7.3 that may be related to the above discussion.
I am writing articles with extensive use of the pagebreak (using JCE editor). After the upgrade the browser page header shows the current page title with the page number. In the article the page title is added to the article title. Previously the browser page header only showed the article title for any page and the article title was left alone (as it should). 
Any suggestions to fix this (until hopefully the Joomla team does by the next upgrade)?

**Comment by zero-24** [comment]
Please open a new issue describing in detail how to reproduce your issue. The issue described in this issue is fixed in 3.7.3 and should not be your problem. Thanks.

**Comment by ghost** [comment]
This is still not fixed properly, because this breaks _any_ pagination on Joomla articles, if no pagebreaks are used in that article. Simply go to any article page without pagebreak, and add ?limitstart=20 to the url.
We have a custom list which has pagination, and now we get a 404 but the page is just fine, since the list is paginated. After I found that it was the Page Break plugin, I've disabled it, but now I can't use page breaks. A simple switch in the plugin settings if a 404 should be thrown, would solve this nicely and would give other plugins still the use of pagination on Joomla article pages.

**Comment by ghost** [comment]
@conflate-nl can you please open a new Issue?

**Comment by eriknzzz** [comment]
Already done https://github.com/joomla/joomla-cms/issues/17127

**Comment by ghost** [comment]
Actually #17127 is not the problem, the problem is on pages which aren't using page breaks, but custom pagination lists. I've created a new Issue #17305
