### ISSUE TITLE
Category Batch Move or Copy dropdown does not display

### ISSUE THREAD

**Issue by boldc** [joomla/joomla-cms#18532]
### Steps to reproduce the issue
Login to Joomla Control Panel
From menu got to Content > Categories
Click a checkbox next to a Category and click on Batch
Look for the line of text "To Move or Copy your selection please select a Category."

### Expected result
A dropdown or list of options ('Move' or 'Copy') from which to select.

### Actual result
The area under the line of text is blank, underneath is the text and option to reverse Category article order

### System information (as much as possible)
Joomla 3.8.2
Issue observed in Chrome and Forefox

System Information:![screen shot 2017-11-08 at 17 26 34](https://issues.joomla.org/uploads/1/5938d0f499e62477c4a4c1ccf86709df.jpg)
Database Version	5.6.37
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.32
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.8.2 Stable [ Amani ] 7-November-2017 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

**Comment by simbus82** [comment]
Did you clear browser cache? i don't have this problem in 3.8.2

**Comment by ghost** [comment]
Can't confirm too. As far as i remember this is fixed in 3.8.2 (but can't find Pull Request so maybe 'm wrong).

**Comment by boldc** [comment]
Hi simbus82, I cleared my Chrome browser cache & restarted my browser and the problem persisted. So I tried Firefox, as I had not previously loaded the website using that browser.  This confirmed the issue.  The site was built with J! 3.8.1 then updated to 3.8.2.

**Comment by hacki65** [comment]
I don't confirm this issue. See screen:
![screenshot-2017-11-9 articles categories - joomla 3 8 - administration](https://user-images.githubusercontent.com/20481746/32604693-dc0faea4-c54e-11e7-9a3c-ce27ff7ca9b7.png)

Also updated from 3.8.1, tested with PHP 5.6.32, 7.0.25 & 7.1.11 - worked as expected.
Try to clear both - browser & Joomla! Cache.

**Comment by boldc** [comment]
Hi hacki65, I tried that and it didn't work.  This seems to be a corner case, as a workaround I manually recreated an identical Category.

**Comment by simbus82** [comment]
@boldc try to reupload the joomla core with Joomla Update, then check&fix the database
https://docs.joomla.org/J3.x:Updating_from_an_existing_version#Checking_Your_Site

**Comment by Quy** [comment]
@franz-wohlkoenig Since this is not reproducible by others and fixed by recreating the categories per OP, maybe close this issue.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18532">issues.joomla.org/tracker/joomla-cms/18532</a>.</sub>
