### ISSUE TITLE
[3.8.2] Editing core Joomla category menu changes the URL structure from previous version

### ISSUE THREAD

**Issue by jreviews** [joomla/joomla-cms#18785]
### Steps to reproduce the issue

In a version prior to Joomla 3.8.2 create a Joomla article category blog menu. The non-SEF URL format is

index.php?option=com_content&view=category&layout=blog&id=100

Upgrade to Joomla 3.8.2, edit the menu, save, and the URL format is now:

index.php?option=com_content&view=category&layout=blog&id=100&filter_tag[0]=

### Expected result

Editing a category menu should not alter it's URL structure

### Actual result

Editing a category menu alters the URL structure

### System information (as much as possible)

Joomla 3.8.2

### Additional comments

This happens because when editing a menu in Joomla 3.8.2,  the "Tag" setting now has a value of "none" that is automatically pre-selected. When saving the menu it changes non-SEF URLs which is not desired, because why would the URL need to change if no changes were made? and it also breaks code that uses the AbstractMenu::getItems class to find those menus because now the menu format has also changed.

**Comment by ghost** [comment]
@csthomas is one of your PR's for this Issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18785">issues.joomla.org/tracker/joomla-cms/18785</a>.</sub>

**Comment by csthomas** [comment]
No, but it is known issue at https://forum.joomla.org/viewtopic.php?f=706&t=956574

**Comment by jreviews** [comment]
As mentioned in the referenced forum post, it is necessary to always remove the "none" tag selection to revert to the original URL format, but most users that edit a menu will not do this, so effectively the URL changes anytime you update the menu.

**Comment by teokolo** [comment]
I confirm the issue on  Joomla 3.8.2 both on old and new category blog menu items, both SEF and non-SEF URLs.

I'm using SEF URLs and the suggested workaround (removing NONE tag and saving) does not work for me.

Steps to reproduce
- Create a category, some articles in it, a category blog menu item
- Access an article inside the category (URL is like site/category-url/33-article)
- Now look at the breadcrumb pointing to category: expected link on breadcrumb us site/category-url but I see site/category-url?filter_tag[0]=

My workaround (very dirty) is replacing ?filter_tag[0]= with "" in file modules/mod_breadcrumbs/tmpl/default.php . I know it's not a breadcrumb problem, but I needed a very fast workaround.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18785">issues.joomla.org/tracker/joomla-cms/18785</a>.</sub>

**Comment by Quy** [comment]
With this PR #18234, it is possible to select multiple tags, therefore, it is no longer necessary to have a NONE value.

In \components\com_content\views\category\tmpl\blog.xml
```
			<field
				name="filter_tag"
				type="tag"
				label="JTAG"
				description="JTAG_FIELD_SELECT_DESC"
				multiple="true"
				>
				<option value="">JNONE</option>
			</field>
```
change to the following should fix this issue:
```
			<field
				name="filter_tag"
				type="tag"
				label="JTAG"
				description="JTAG_FIELD_SELECT_DESC"
				multiple="true"
			/>
```

@teokolo Can you please test? I will do a PR if test is successful.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/18981

**Comment by teokolo** [comment]
My problem is not solved. If I look at breadcrumbs, wrong url is still there .
Maybe it's a different bug, let me know if it's better to open a new and detailed one.

**Comment by ghost** [comment]
@teokolo if #18981 don't solve the Issue and no other Issue is still open please create an new one.
