### ISSUE TITLE
Override CategoryBlog is not executed on Linux

### ISSUE THREAD

**Issue by PieterVuylsteke** [joomla/joomla-cms#19007]
### Steps to reproduce the issue

In the "native" com_component one finds two series of files in the directory
<root>\components\com_content\views\category\tmpl
default.php and its dependents --> is executed for a articlelist
blog.php and its dependents. -> is executed for a blogcategory

In the override I installed one series of files :
template/html/com_content/blogPieter.php and five other files (including the xml file)

Then I am able to select the blogPieter in a menu item I did create. 

BUT, 
when I do execute that menu item, the article list layout is executed 
thus the 
<root>\components\com_content\views\category\tmpl\default.php

instead of my blogPieter from the override.

### Expected result
Execution of my blogPieter

### Actual result
Execution of the article list (default.php)

### System information (as much as possible)
Bug is not present in joomla 3.8.2 on windows, but it is present on linux with joomla 3.8.2

### Additional comments
when I change  <template>/html/com_content/blogPieter.php (and the other files) to 
template/html/com_content/blog.php

and I change my menu item to categoryblog, I do get the overriden version of the blog.php. 
(blogPieter may then of course be removed)

Thus the BUG is, on linux  : 
1. I can select in the administrator environment the new layout from the override in the template

2. It is NOT executed, it is the default.php, thus the articlelist that is executed instead.
as can be seen in 
http://www.fotografiepieter.be/portfolio/test-telt-niet-wej

3. If I do a direct override of blog.php (and the other four files) I do get that adapted version for blogcategory, as can be seen in http://www.fotografiepieter.be/blog

**Comment by ghost** [comment]
changed Title so its clear its about "on Linux".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19007">issues.joomla.org/tracker/joomla-cms/19007</a>.</sub>

**Comment by brianteeman** [comment]
Sounds like a typical example of case sensitivity

Remember windows is not case sensitive but linux is

**Comment by PieterVuylsteke** [comment]
that was also my idea, I checked it (some days ago) and it is not the case. 
As can be seen in this printscreen :
![image](https://user-images.githubusercontent.com/34317326/33682147-e4dcdce0-dac6-11e7-90fd-d441f741f329.png)

**Comment by Webdongle** [comment]
Have you tried without using camelCase for a file name ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19007">issues.joomla.org/tracker/joomla-cms/19007</a>.</sub>

**Comment by PieterVuylsteke** [comment]
That did it. I changed the name of my files to blogpieter, and now it is found. 

Strange, is that a rule in joomla not to use uppercase ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19007">issues.joomla.org/tracker/joomla-cms/19007</a>.</sub>

**Comment by PieterVuylsteke** [comment]
In the meantime I upgraded to 3.8.3 and see the same thing: with uppercase it does not work, with only lowercase it is fine.

I changed the uppercase title simply through filezilla, and even did not have to go to the administrator to have correct version. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19007">issues.joomla.org/tracker/joomla-cms/19007</a>.</sub>

**Comment by ghost** [comment]
Closed as Issue is solved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19007">issues.joomla.org/tracker/joomla-cms/19007</a>.</sub>

**Comment by SemaphoreOxalis** [comment]
And I think this old "issue"is still not documented anywhere (my new colleague who is disconering J! just have spend 2 hours on this lowercase thing) How can we update the official doc ?

**Comment by Webdongle** [comment]
> And I think this old "issue"is still not documented anywhere (my new colleague who is disconering J! just have spend 2 hours on this lowercase thing) How can we update the official doc ?

This is an issue with Windows and the user manually using camelCase.  You will notice that Menu/Article Titles are always lowercase.
