### ISSUE TITLE
[4.0] Password Strength Bar Width is 100%.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#19227]
### Steps to reproduce the issue
Go to Joomla backend > User Manager >> New User
You can see the Password Strength Bar is 100% wide.

### Expected result
It should just be as wide as the field itself.

### Actual result
![image](https://user-images.githubusercontent.com/3968575/34447021-ff08ccf2-ecad-11e7-86d6-018b088f6adb.png)

### System information (as much as possible)
Joomla 4.0.0-dev

### Additional comments
PHP 7

**Comment by ghost** [comment]
Issue confirmed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>

**Comment by anuragteapot** [comment]
change build to <code>4.0-dev</code><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>

**Comment by ghost** [comment]
@Anu1601CS done, thanks for Hint.

**Comment by S2606** [comment]
can i work in this??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>

**Comment by dgrammatiko** [comment]
@S2606 sure, just make a pr against https://github.com/joomla/joomla-cms/pull/19231

**Comment by dgrammatiko** [comment]
Actually this is solved with https://github.com/joomla/joomla-cms/pull/19231

**Comment by anuragteapot** [comment]
@dgt41 I have tested this on pr #19231 this issue is still present.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>

**Comment by amone4** [comment]
I did manage to solve this bug, by appending some code to passwordstrength.js (passwordstrength.min.js), in an installed version of the CMS. But the file I modified is quite different than what I found after cloning the repository https://github.com/joomla/joomla-cms

I wanted to ask how the above file is being generated. The version that I installed was from https://www.joomla.org/announcements/release-news/5718-joomla-4-0-alpha-1-release.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>

**Comment by dgrammatiko** [comment]
@amone4 please do a PR against #19231. The passwordstrength.min.js is going to be removed

**Comment by anuragteapot** [comment]
@amone4 clone the latest dev from here https://github.com/joomla/joomla-cms/tree/4.0-dev
And make PR against  #19231

**Comment by Quy** [comment]
Fixed in PR #19231<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19227">issues.joomla.org/tracker/joomla-cms/19227</a>.</sub>
