### ISSUE TITLE
Router builds erroneous site routes when invoked from admin code

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#20070]
### Steps to reproduce the issue
In admin side code:

use \Joomla\CMS\Router\Router;
$router = Router::getInstance('site');
$routedUrl = $router->build('index.php?option=com_content&view=article&id=1&Itemid=1');
$routedUrlAsString = $routedUrl->toString();

### Expected result
For menu item with alias 'foo' pointing at article 'bar':

https://my.site.tld/foo/bar

### Actual result

https://my.site.tld/administrator/foo/bar

### Additional comments

Method SiteRouter::build($url) prefixes the constructed SEF url with \JUri::base(true). When invoked from within admin code, JUri::base() returns an uri containing '/administrator', which is not the intention for a site SEF url.

**Comment by mbabker** [comment]
This is probably addressed by https://github.com/joomla/joomla-cms/pull/16879 and I'm not so sure there is anything sane to be done for 3.8 other than having a helper method that parses and removes the `/administrator` segment.

**Comment by pjdevries** [comment]
As far as I can see, the use of JUri::base() seems to be the main culprit. Other than that the constructed SEF url looks fine.

For my purpose, removing `/administrator` is exactly what I do now :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20070">issues.joomla.org/tracker/joomla-cms/20070</a>.</sub>

**Comment by brianteeman** [comment]
As #16879 has been merged I am going to close this at this time. It can always be reopened if needed if that didnt solve it.
