### ISSUE TITLE
Error decoding JSON data: Syntax error

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#20674]
### Steps to reproduce the issue
Install nightly staging
Under Content > Fields, create a custom field.

### Actual result
Error decoding JSON data: Syntax error 
\libraries\vendor\joomla\registry\src\Format\Json.php:72

```

# | Function | Location
-- | -- | --
1 | () | JROOT\libraries\vendor\joomla\registry\src\Format\Json.php:72
2 | Joomla\Registry\Format\Json->stringToObject() | JROOT\libraries\vendor\joomla\registry\src\Registry.php:370
3 | Joomla\Registry\Registry->loadString() | JROOT\administrator\components\com_fields\models\field.php:334
4 | FieldsModelField->getItem() | JROOT\libraries\src\MVC\View\HtmlView.php:423
5 | Joomla\CMS\MVC\View\HtmlView->get() | JROOT\administrator\components\com_fields\views\field\view.html.php:52
6 | FieldsViewField->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:672
7 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\administrator\components\com_fields\controller.php:57
8 | FieldsController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_fields\fields.php:29
10 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:382
11 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:357
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:195
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51
```

### System information (as much as possible)
nightly staging

**Comment by mbabker** [comment]
Should be fixed by https://github.com/joomla/joomla-cms/pull/20663 (nightly build will update in 4 hours from now)

**Comment by ghost** [comment]
closed as stated above.

**Comment by Quy** [comment]
This is still an issue with nightly build: Wednesday, 06 June 2018 02:03:15 UTC

**Comment by ghost** [comment]
Reopened, thanks for Info.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20674">issues.joomla.org/tracker/joomla-cms/20674</a>.</sub>

**Comment by mbabker** [comment]
Fixed by https://github.com/joomla/joomla-cms/pull/20675 now I'm going to try to go to bed.
