### ISSUE TITLE
Invalid variable type declared

### ISSUE THREAD

**Issue by soulevilx** [joomla/joomla-cms#21071]
### Steps to reproduce the issue
Check: libraries/src/Layout/LayoutHelper.php
Line 57
`* @param   object  $displayData  Object which properties are used inside the layout file to build displayed output
`

### Expected result
$displayData should be declared as array 

### Actual result
But it's declared as object

**Comment by ghost** [comment]
@Quy can you please have a Look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21071">issues.joomla.org/tracker/joomla-cms/21071</a>.</sub>

**Comment by schnuti** [comment]
Most, if not all, core JLayouts use an object for $displayData. In the beginning of JLayout the documentation said "use an array". If I understand it correct, the object data is sent by reference, array data not.  
e.g.
```
LayoutHelper::render('joomla.edit.title_alias', $this)

$form  = $displayData->getForm();
```

**Comment by ghost** [comment]
@jooservices is this Issue solved by Comment of @schnuti?

**Comment by soulevilx** [comment]
Hi there
Sorry but i don't think so. Even in Joomla! we still have this "issue"

`administrator/components/com_users/views/levels/tmpl/default.php`
**line 40**
`<?php echo JLayoutHelper::render('joomla.searchtools.default', array('view' => $this, 'options' => array('filterButton' => false))); ?>`

So, as you can see param 2 is array.
But inspect
**JLayoutHelper::render**
we have function
`public static function render($layoutFile, $displayData = null, $basePath = '', $options = null)`

and docblock is

> * @param   object  $displayData  Object which properties are used inside the layout file to build displayed output

So, I think issue still there.

**Comment by ghost** [comment]
@jooservices Thanks for Comment.

**Comment by schnuti** [comment]
My comment was on the title of the issue. Object is valid as also array or string or null.
If someone wants to exchange Object with Data in a PR it would be neutral and correct.

**Comment by N6REJ** [comment]
Gotta love subtleties

**Comment by Quy** [comment]
Fixed in PR #21837<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21071">issues.joomla.org/tracker/joomla-cms/21071</a>.</sub>
