### ISSUE TITLE
[4.0] Workflows - delete stage

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#21601]
### Steps to reproduce the issue
Try to delete an unused stage

0 Call to undefined method PlgContentJoomla::_canDeleteStates()
```


Call stack
--
# | Function | Location
1 | () | JROOT\plugins\content\joomla\joomla.php:419
2 | PlgContentJoomla->onContentChangeState() | JROOT\libraries\src\Plugin\CMSPlugin.php:287
3 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:402
4 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:111
5 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\libraries\src\MVC\Model\AdminModel.php:1051
6 | Joomla\CMS\MVC\Model\AdminModel->publish() | JROOT\administrator\components\com_workflow\Model\StageModel.php:329
7 | Joomla\Component\Workflow\Administrator\Model\StageModel->publish() | JROOT\libraries\src\MVC\Controller\AdminController.php:230
8 | Joomla\CMS\MVC\Controller\AdminController->publish() | JROOT\libraries\src\MVC\Controller\BaseController.php:717
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\Dispatcher.php:162
10 | Joomla\CMS\Dispatcher\Dispatcher->dispatch() | JROOT\libraries\src\Dispatcher\LegacyDispatcher.php:72
11 | Joomla\CMS\Dispatcher\LegacyDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:354
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:111
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:154
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:242
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
16 | require_once() | JROOT\administrator\index.php:36


```

**Comment by brianteeman** [comment]
Note 
- Deleting a transition works
- Changing _canDeleteStates to _canDeleteStages gives a different error Table 'joomla_db.array' doesn't exist

**Comment by wilsonge** [comment]
I would imagine this should be fixed by https://github.com/joomla/joomla-cms/pull/21579 (I merged 4.0 into that last night so shouldn't give the 500 anymore)

**Comment by brianteeman** [comment]
Sorry not fixed

0 Call to undefined method PlgContentJoomla::_canDeleteStates()

**Comment by wilsonge** [comment]
I haven't merged it into 4.0 - it's an open pr that needs testing.

**Comment by brianteeman** [comment]
sorry I misread your comment

**Comment by brianteeman** [comment]
closed as it is fixed by #21579
