### ISSUE TITLE
[4.0] com_content ACL display problem in frontend

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#22232]
There is a problem in the management of front-end com_content ACL display rights.

If a user is a member of a group with the right to "edit" or "edit own", but he does not have the right to "edit state", he can not display an article with "unpublished " state in front end.

This is a problem because an author or editor (in Joomla base ACL)  can not edit an article being written before a publisher publish it.

With the arrival of the workflow in Joomla4 it would be a pity that this problem is not corrected.

The right of display an article in front should be based 1st on "modify its elements" and "modify" and in this case allow the display even if the status of the item is "unpublished".

**Comment by ghost** [comment]
Can a ACL-experienced one comment as this Issue is open for a Week having Status "New"?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22232">issues.joomla.org/tracker/joomla-cms/22232</a>.</sub>

**Comment by brianteeman** [comment]
It's a feature request @franz-wohlkoenig

**Comment by ghost** [comment]
Thanks for Info @brianteeman. Category "Feature Request" is now added in Issue Tracker.

**Comment by rolandalsace** [comment]
No, it's not a feature request.
I think it's realy a bug.
It is not normal that when an editor saves an article, that there is no more access after.

**Comment by alikon** [comment]
sorry it's for j3 or  for j4 ?

**Comment by infograf768** [comment]
Looks like it is for j3 but looks a bit late for 3.9.
comment above:
> With the arrival of the workflow in Joomla4 

In fact I have always wished we had 3 buttons in frontend: `Save`, `Save & Close` and a `Preview` button (+ the Cancel one). This would allow Authors (with permissions only set to Create and Edit Own) to check in frontend the display result of their proposed article after `Save` (as we need an article id) and before a `Save & Close` which would close the edit form.
This would still let Editors with the `Edit` permission to control the content proposed after a `Save & Close` and a Publisher to decide of the article State.

In j4, `Preview` was added when editing an article in backend grace to a new helper `PreviewHelper`

It would indeed be a new feature, even if it is only for J4.

**Comment by ghost** [comment]
needs a j4-Label.

**Comment by ghost** [comment]
@infograf768 can you please add a j4-Label?

**Comment by ghost** [comment]
@HLeithner can we test pull request on this ?

**Comment by HLeithner** [comment]
There seams to be no pull request yet

**Comment by rytechsites** [comment]
In J4, if there is an option for 'PREVIEW', if we at least allow users to EDIT their own article on the FRONT END while it's NOT PUBLISHED, then you will meet the need of previewing... editing, etc.

**Comment by rytechsites** [comment]
I see this as 2 issues...from the front end (I'm sorry I don't know how to fix)

1. to DISPLAY unpublished articles for authors, if they 'own the article', and if they have 'edit own', as a setting.  I know there is a module that shows all articles owned by an author, but it doesn't allow you to display unpublished ones.  (Instead I'm using a separate tool to display Latest News enhanced, but could be done with core joomla)

2. to be able to EDIT the unpublished article
Once you find that article, you should be able to EDIT it as the 'owner' of the article, and if you have edit own.

thanks,
Laura

**Comment by obuisard** [comment]
After running into the same issue for several clients (surprisingly on the same week), I really think it is a bug that should be addressed in Joomla 3 (since many sites will not jump into Joomla 4 right away but still need the fix).

Authors with access permissions: edit and edit-own can edit everyone's article, published or not.
Here, the author 'jd' can access his unpublished articles.

![edit_edit_own](https://user-images.githubusercontent.com/5964177/75489867-10755680-5981-11ea-8b9e-91a4f1848ef8.jpg)

Authors with access permission: edit-own (only) can only edit their published articles.
'jd' cannot access his unpublished articles.

![edit_own](https://user-images.githubusercontent.com/5964177/75490009-529e9800-5981-11ea-9e34-2ff63fea57b9.jpg)

There is no way for authors to retrieve an unpublished article from the frontend, which totally breaks the default workflow.

**Comment by alexandreelise** [comment]
Something to work on for sure. I was experimenting some ideas using a system plugin mainly for Joomla! 3 regarding a similar issue.
Maybe I can help to work on this when I have some time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22232">issues.joomla.org/tracker/joomla-cms/22232</a>.</sub>

**Comment by AndySDH** [comment]
This has been first reported as an issue in Joomla over 4 years ago (with multiple issues marked as duplicate and closed), and in 2021 is still not solved :(
