### ISSUE TITLE
Invisible Captcha stopped working

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#24181]
### Steps to reproduce the issue

After Updating to Joomla 3.9.4 the Joomla captcha Field (core) returns always invalid value - users can't register anymore when captcha is enabled.

### Expected result
Working

### Actual result
Does not work here

### System information (as much as possible)
Joomla 3.9.4

**Comment by twister65** [comment]
Please, could you give more information.
I successfully register a new user with recaptcha invisible and Joomla 3.9.4.
Perhaps, your settings have been changed.

**Comment by coolcat-creations** [comment]
So the only thing that was changed was the Joomla Version. And the Error message was unfortunately just "Captcha is invalid"... If the key is wrong it would show another error message on the Google Badge itself. Not sure how to debug.

**Comment by twister65** [comment]
Perhaps, it could help. In the admin console, go to "Advanced Settings" for your key, and verify the "Domain/Package Name Validation" box is checked.
https://www.google.com/recaptcha/admin
Otherwise, see:
https://developers.google.com/recaptcha/docs/domain_validation
I don't think that your problem is due to Joomla 3.9.4 because recaptcha plugin has not been modified.

**Comment by twister65** [comment]
You can also see these topics in the forum, they can solve your issue:
https://forum.joomla.org/viewtopic.php?t=970093
https://forum.joomla.org/viewtopic.php?t=970327

**Comment by twister65** [comment]
It has been solved here:
https://forum.joomla.org/viewtopic.php?t=968779
https://forum.joomla.org/viewtopic.php?t=968430

**Comment by coolcat-creations** [comment]
Thank you - probably it will be this issue

>  The problem is solved, looks like the Captcha is using the function CurlTransport.php that was disabled in the last updates of PHP for security reason. So the server administrator enabled it. Thanks a lot for your support

I am checking with the hoster.

EDIT: Curl is not disabled, keys are correct, issue not solved. Having to use 3rd party plugin instead of core...

**Comment by wilsonge** [comment]
Reopening as you edited to say it's not solved

**Comment by softforge** [comment]
I managed to find a test site on 3.9.3
I signed it up and added the keys tot he plugin. I activated the plugin and turned it on in the system area and then observed the invisible Captcha working on a form.
I then updated the site to 3.9.4 so that was the only change and observed that all was still working as it should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24181">issues.joomla.org/tracker/joomla-cms/24181</a>.</sub>

**Comment by Quy** [comment]
@coolcat-creations Is this still an issue with v3.9.6?

**Comment by coolcat-creations** [comment]
Yes, but I gave up trying and use 3rd party captchas on all sites. I guess its related to that it seems to use mootools.
