### ISSUE TITLE
[4.0] Unaccesible editor after window resize

### ISSUE THREAD

**Issue by Puneet-Jain-18** [joomla/joomla-cms#24547]
### Steps to reproduce the issue
Go to backend 
Administrator/articles/New
Enter Some Text in the editor

Resize browser window to a **small width** 

### Expected result

 The editor is Still accessible when the width of window is set to normal  

### Actual result

Unable To enter any Text in the Editor before/after resizing back to normal screen
(JS Errors are produced at the console)

### System information (as much as possible)

Joomla! 4.0.0-alpha8-dev

### Additional comments
The issue needs confirmation.

**Comment by brianteeman** [comment]
What are the js errors?

**Comment by Puneet-Jain-18** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/34083630/55898687-c3f62080-5be0-11e9-85a5-887a9e4b6786.png)


Actually I removed the code which was producing JS errors (to check) but the issue still persists

**Comment by bahl24** [comment]
@brianteeman The errors in console don't effect the behaviour of the editor & have been solved in #24548 , is the editor bug in Joomla or TinyMICE?

**Comment by ghost** [comment]
Closed as having Pull Request #24548

**Comment by Puneet-Jain-18** [comment]
@franz-wohlkoenig the PR doesn't solve the error, I issue is not related to JS errors. It's something else.

**Comment by bahl24** [comment]
Yes, @franz-wohlkoenig kindly reopen this, I have mentioned in the PR that editor is still inaccessible.
It only solves the JS error

**Comment by brianteeman** [comment]
I can not repliacte this any more

**Comment by alikon** [comment]
no more replicaple, fixed elesewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24547">issues.joomla.org/tracker/joomla-cms/24547</a>.</sub>
