### ISSUE TITLE
[4.0] Alpha9: Wrong download links in XMLs

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#24638]
### Steps to reproduce the issue
Joomla 4.0 NightlyBuilds download link (found on https://developer.joomla.org/nightly-builds.html)
is https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha8-Alpha-Development-Full_Package.zip
its version is 4.0.0-alpha8-Alpha.
However next major list XML contains old version - 4.0.0-alpha8-dev. https://update.joomla.org/core/nightlies/next_major_list.xml

This issue happens from time to time.
Last time it happened https://github.com/joomla/joomla-cms/issues/24154
### Expected result

https://update.joomla.org/core/nightlies/next_major_list.xml
4.0.0-alpha8-Alpha

### Actual result
4.0.0-alpha8-dev

**Comment by alikon** [comment]
should be fixed now https://github.com/joomla/update.joomla.org/pull/125

**Comment by ghost** [comment]
Closed as Issue fixed. Please reopen if needed.

**Comment by dmitriy-cloudaccess** [comment]
No, it isn't fixed.
https://update.joomla.org/core/nightlies/next_major_extension.xml - still contains 4.0.0-alpha8-dev.

https://developer.joomla.org/nightly-builds.html - Download link is `https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha8-Alpha-Full_Package.zip`.
version in download link is `4.0.0-alpha8-Alpha`.

Links are still broken. Automatic updates aren't available

**Comment by alikon** [comment]
see https://github.com/joomla/update.joomla.org/pull/126

**Comment by dmitriy-cloudaccess** [comment]
But what about actual download link name?
I can get the latest NB 4.0 from https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha8-Alpha-Full_Package.zip 
Check it here https://developer.joomla.org/nightly-builds.html

But XMLs say the download link is https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha9-dev-Full_Package.zip (File doesn't exist)

Scripts still can't download updates using links from XMLs

**Comment by alikon** [comment]
if i'm not wrong the cron job from nightly builds runs once a day, and the last one....

`These packages were last built: Friday, 19 April 2019 02:00:39 UTC`

**Comment by HLeithner** [comment]
I fixed the version string in j4 branch and triggered a rebuild of the nightly, now everything should be ok again.

**Comment by ghost** [comment]
@alikon true, nightly run one a day.

**Comment by dmitriy-cloudaccess** [comment]
Everything is fine now. Thanks guys!

**Comment by dmitriy-cloudaccess** [comment]
Reopening.
Download link on https://developer.joomla.org/nightly-builds.html is https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha9-dev-Development-Full_Package.zip (version is 4.0.0-alpha9-dev)

https://update.joomla.org/core/nightlies/next_major_list.xml points to version 4.0.0-alpha10-dev.
Can't download update.

**Comment by HLeithner** [comment]
The reason is that our build server can't deploy the nightly builds at the moment, we come back when we fixed this.

**Comment by mbabker** [comment]
Fixed.  An update was needed on the build server after rotating SSL certificates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24638">issues.joomla.org/tracker/joomla-cms/24638</a>.</sub>

**Comment by dmitriy-cloudaccess** [comment]
@HLeithner @mbabker This issue appeared again.
Download links from https://update.joomla.org/core/nightlies/next_major_extension.xml is:
https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha11-dev-Development-Update_Package.zip
Live link is: https://developer.joomla.org/nightlies/Joomla_4.0.0-alpha11-Alpha-Update_Package.zip

version string differs.

**Comment by mbabker** [comment]
Can we stop giving people a reason to re-open this every time a release is tagged?

**Comment by HLeithner** [comment]
has been fixed with https://github.com/joomla/joomla-cms/commit/1f92efeee8cec926a11f170ce1f5888419493a64

And yes michael we should be more careful on creating new releases so this doesn't happen again or make our tooling better.

**Comment by zero-24** [comment]
> has been fixed with 1f92efe

Partly yes but the update server still points to alpha11 and not alpha12 as the update server PR has not been merged until now https://github.com/joomla/update.joomla.org/pull/134 and I don't like to merge my own PRs on the updater repo ;)
