### ISSUE TITLE
[4.0] CPanel unreadable fields in some windows sizes

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#27490]
Example:
<img width="1456" alt="Screen Shot 2020-01-12 at 08 23 38" src="https://user-images.githubusercontent.com/869724/72215600-19b37c80-3515-11ea-9bcb-630d27f1c795.png">

I consider this as a release blocker.

**Comment by brianteeman** [comment]
it's an issue but its not a release blocker as its purely cosmetic and doesnt break functionality etc

**Comment by infograf768** [comment]
Release as is. An d then wonder why some quit Joomla.

**Comment by Quy** [comment]
Thus #25891 should be considered.

**Comment by infograf768** [comment]
@ciar4n 
Could you look at this?

**Comment by ciar4n** [comment]
https://github.com/joomla/joomla-cms/pull/27153 should resolve this?

**Comment by infograf768** [comment]
Will test tomorrow

**Comment by Quy** [comment]
It is still an issue with #27153. It should be one column like the other settings under `Component`.

![27490](https://user-images.githubusercontent.com/368084/72224300-cef22e80-352d-11ea-8363-954a3664993d.jpg)

**Comment by brianteeman** [comment]
just do a media query

**Comment by ciar4n** [comment]
Currently, the media queries already exist... https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/blocks/_layout.scss#L55-L81. Adjusting them to display single column sooner might solve the issue.

Going by @Quy 's screenshot, #27153 appears to resolve the field breaking out of its container and the unequal column widths, but not the column #.

**Comment by ciar4n** [comment]
Considering there is a sidebar and a component menu in the global config, even at 1400px this page is still a bit crammed for 2 columns...

![image](https://user-images.githubusercontent.com/2803503/72235786-f13a8980-35cb-11ea-9835-7f90c9d9ac02.png)

**Comment by infograf768** [comment]
In j3 the sidebar is automatically reduced with window width and we do not have the enormous left menu bar...

**Comment by C-Lodder** [comment]
If you fix the UX, you fix the issue. I have raised this before

**Comment by alikon** [comment]
closing as we have a pr
please test #27613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27490">issues.joomla.org/tracker/joomla-cms/27490</a>.</sub>
