### ISSUE TITLE
[4.0] Password toggler

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#28256]
### Steps to reproduce the issue
Mixing the use of fa-eye and icon-eye in the markup and javascript causes issues

@SharkyKZ some of this comes from a recent pr of yours and I am not sure how to proceed. As it looks like you changed your mind about using icon- or fa- during the pr

### Step 1 - page load (com_users)
`<span class="fas fa-eye" aria-hidden="true"></span>`
![image](https://user-images.githubusercontent.com/1296369/76127550-d697f600-5ff9-11ea-9b71-3bb709790578.png)

### Step  2 - after clicking on above
`<span class="fas fa-eye icon-eye-close" aria-hidden="true"></span>`
![image](https://user-images.githubusercontent.com/1296369/76127630-0ba44880-5ffa-11ea-8e11-c0b989d1ddf9.png)

### Step 3 - after clicking on above
`<span class="fas fa-eye icon-eye" aria-hidden="true"></span>`
![image](https://user-images.githubusercontent.com/1296369/76127577-e7e10280-5ff9-11ea-9ccd-1f0ad6ee36e8.png)

## Why does this matter?
The icons/buttons in step 2 & 3 are a different width to step 1

**Comment by SharkyKZ** [comment]
I kept old classes as advised by you (https://github.com/joomla/joomla-cms/pull/27733#issuecomment-580641134). #27686 converted classes in layouts to FA but forgot to update the JS.

The change is simple to make but to me it's still unclear which classes are to be used.

**Comment by brianteeman** [comment]
Yes I am confused too

**Comment by N6REJ** [comment]
having both classes is wrong.
I've given up on the which iconset classes are better discussion.  Right now two are supported.  If my work has done anything it's revealed that only a single set should be used.  Whether its svg, fa font or icomoon doesn't matter.  But it should be singular to stop confusion.

**Comment by SharkyKZ** [comment]
Closing as this was fixed in https://github.com/joomla/joomla-cms/pull/28075.

**Comment by brianteeman** [comment]
There is still an issue on the login screen - the width changes from 18px to 20px

![icon](https://user-images.githubusercontent.com/1296369/88370585-3107d800-cd8a-11ea-871c-9ec3f9351ee0.gif)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30176.
