### ISSUE TITLE
[4.0beta] toggle plugin status via status icon not working

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#29378]
### Steps to reproduce the issue
in plugin manager, click on plugin status to disable plugin
![screen shot 2020-06-02 at 07 19 49](https://issues.joomla.org/uploads/1/fe91bddba3253338c06d30bfae5bad23.jpg)

### Expected result
plugin disabled

### Actual result
plugin NOT disabled

### System information (as much as possible)
4.0.beta

### Additional comments
same for enabling plugin

**Comment by richard67** [comment]
@Ruud68 I think this has been fixed with #29356 . Could you check, and if it's fixed close this issue? Thanks in advance.

**Comment by Ruud68** [comment]
@richard67 I am on the nightly so that value was already set. So issue is still there

**Comment by richard67** [comment]
@Ruud68 Also made a new installation with that nightly so the database is up to date?

**Comment by Ruud68** [comment]
Nope as that change you pointed out didn't have a database change. will do a fresh install.
But just to be sure: do you have the issue as well or is it working for you?

**Comment by richard67** [comment]
@Ruud68 It's working for me. Please try again with making a new installation into an empty database or with creating a new database.

**Comment by Ruud68** [comment]
Yes, just did a fresh install and issue is not present. Closing this one leaving me clueless as to how that happened in the first place :S
Thanks for the follow up @richard67 #appreciated

**Comment by richard67** [comment]
@Ruud68 Thanks for reporting and testing and keeping an eye open. Yes, sometimes it can happen it was a false alarm, but better this way than the other way round, no alarm when necessary.
