### ISSUE TITLE
[4.0b1] Folder creation error message not shown 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29499]
### Steps to reproduce the issue

Try to create a folder in media manager in Joomla 4 

Test 1: Try to create a folder with the name of a folder that already exists.
Test 2: Try to create a folder called `../tmp/something`

### Expected result

Test 1: "Error: A Folder already exists with that name"
Test 2: "You cannot use relative paths"

### Actual result

Test 1: Generic Error message and JSON XHR response of `{"success":false,"message":"","messages":null,"data":null}`

<img width="206" alt="Screenshot 2020-06-08 at 17 34 35" src="https://user-images.githubusercontent.com/400092/84057132-21d1f400-a9af-11ea-9966-858f6a14db2f.png">

Test 2: Generic Error Message, and a blank space above message and JSON AJAX response of 

```
{"success":false,"message":"Joomla\\CMS\\Filesystem\\Path::check() - Use of relative paths not permitted","messages":null,"data":null}
```

<img width="851" alt="Screenshot 2020-06-08 at 17 40 27" src="https://user-images.githubusercontent.com/400092/84057155-2ac2c580-a9af-11ea-9bdc-e5f0dce90a37.png">

**Comment by ghost** [comment]
- Issue 1 confirmed.
- Issue 2 `a blank space above message`confirmed, message is:
![Screenshot_2020-09-21 Media - fw4 - Administration(1)](https://user-images.githubusercontent.com/70466955/93769641-61011980-fc1b-11ea-8bc6-ad157826c024.png)

**Comment by PhilETaylor** [comment]
Tested again today. 

Issue 1 is that when you attempt to create a folder that already exists the modal hides the error message and a console.log message is also logged.

<img width="900" alt="Screenshot 2021-04-25 at 17 04 45" src="https://user-images.githubusercontent.com/400092/116000646-097bbf80-a5e9-11eb-8ae4-008d61bfb7a1.png">


Issue two, when trying to create a folder called `../tmp/something`  the modal background hides the issue like the issue 1 above, however also the PHP Classname and Method name are exposed and we should not be displaying PHP Classnames/methods in error messages - we have removed a few of these recently - its not user friendly. 

There is no longer a blank space above the message, you get a generic "Error creating folder" message in that space today. 

<img width="997" alt="Screenshot 2021-04-25 at 17 11 09" src="https://user-images.githubusercontent.com/400092/116000712-3e881200-a5e9-11eb-98d5-1558aaa3ed1a.png">

**Comment by dgrammatiko** [comment]
> Issue 1 is that when you attempt to create a folder that already exists the modal hides the error message and a console.log message is also logged.

The problem is that the message should be rendered inside the modal

> Again the console.log message needs removing

All the console logs were placeholders, there should be a better way to handle the errors. I'll have a look on the reported issues later this week unless someone is faster

**Comment by laoneo** [comment]
@dgrammatiko would it help to move the system message element into the modal?

**Comment by dgrammatiko** [comment]
This should have been fixed

**Comment by brianteeman** [comment]
The modal still hides the error message as reported https://github.com/joomla/joomla-cms/issues/29499#issuecomment-826348957 and the 409 conflict reported still exists
