### ISSUE TITLE
[4.0b1] Two Factor in Users List uses different icons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29508]
### Steps to reproduce the issue

Enable the 2FA plugins in Joomla 4
visit the users list

### Expected result

Consistent use of icons ticks and crosses

### Actual result

different X and tick for non enabled two factor users

<img width="530" alt="Screenshot 2020-06-08 at 19 34 13" src="https://user-images.githubusercontent.com/400092/84067237-0c64c600-a9bf-11ea-9856-60c35a67231a.png">

**Comment by N6REJ** [comment]
pretty sure this is fixed by https://github.com/joomla/joomla-cms/pull/28075

**Comment by PhilETaylor** [comment]
> pretty sure this is fixed by #28075

Nope...

<img width="783" alt="Screenshot 2020-06-09 at 19 19 43" src="https://user-images.githubusercontent.com/400092/84185008-451ba280-aa86-11ea-9b28-d05d5bbe86e9.png">
<img width="373" alt="Screenshot 2020-06-09 at 19 20 30" src="https://user-images.githubusercontent.com/400092/84185026-4ea50a80-aa86-11ea-8363-8dbb393b2a16.png">

**Comment by Quy** [comment]
Fixed in #28075 pending to be merged.

![29508](https://user-images.githubusercontent.com/368084/84194992-ade92780-aa52-11ea-9039-9f154381c23a.png)

**Comment by PhilETaylor** [comment]
well I applied that patch with the patch tester and it did not resolve the problem for me. I'll try it again

**Comment by Quy** [comment]
Sometimes Patch Tester fails. You can use the download package/installer in the footer of the PR. Click `Show all checks` link where there is a Download link. https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/28075/downloads/32886/

**Comment by PhilETaylor** [comment]
Well if you are sure, I take your word for it.

**Comment by Quy** [comment]
You can see in my screenshot. I will keep an eye on this issue until if/when #28075 is merged. Thanks for the report.

**Comment by N6REJ** [comment]
@PhilETaylor patch tester doesn't do npm ci which is needed in this case.

**Comment by PhilETaylor** [comment]
Thank you
