### ISSUE TITLE
[4.0] Page break modal unstyled

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29992]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Welcome to your blog
Click cog -> click edit (to edit the article)

Click "CMS Content" button in editor
Select Page Break

### Expected result

Nice and padded layout in modal

### Actual result

<img width="1356" alt="Screenshot 2020-07-05 at 15 22 59" src="https://user-images.githubusercontent.com/400092/86534823-7f386280-bed3-11ea-9954-8ab32d45749a.png">

### System information (as much as possible)

safari on Mac

### Additional Information 

Backend modal looks like this:
<img width="621" alt="Screenshot 2020-07-05 at 15 24 53" src="https://user-images.githubusercontent.com/400092/86534844-b575e200-bed3-11ea-8668-fd621f1ae59b.png">

**Comment by Quy** [comment]
Fixed in #30038. Padding/spacing between fields reported in #29138.

![29992](https://user-images.githubusercontent.com/368084/88442478-89aa9580-cdc9-11ea-96c0-f6ccbbffe582.png)

**Comment by PhilETaylor** [comment]
I would not call that fixed. all it does is gives it a little padding to the left.   Its still not really styled.

**Comment by Quy** [comment]
The styling issue is same as #29138 due to using Boostrap’s classes and Bootstrap not loaded on the front end.

**Comment by PhilETaylor** [comment]
frontend currently looking like this with border of textboxes disappeared:

<img width="366" alt="Screenshot 2020-10-02 at 19 50 01" src="https://user-images.githubusercontent.com/400092/94959100-8417ad00-04e8-11eb-8e68-20181f01bbb0.png">

**Comment by infograf768** [comment]
Can't reproduce the border issue:
<img width="385" alt="Screen Shot 2020-10-03 at 10 00 14" src="https://user-images.githubusercontent.com/869724/94986476-73564e00-055f-11eb-865e-64f877453871.png">

Safari, Firefox.

**Comment by gostn** [comment]
pr #30889

**Comment by Quy** [comment]
Please confirm this is fixed with the merged of BS5. Thanks.

![page-break](https://user-images.githubusercontent.com/368084/105621362-8a91a380-5dbb-11eb-9c02-8f18af6462fc.png)
