### ISSUE TITLE
[4.0] Feedback: Migration to V4

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#30358]
### Steps to reproduce the issue
1. Migrate from V3.9.20 to V3.10 Alpha
2. Try to mgrate to V4  Beta 3

### Expected result
Step1: successfully Migration to V3.10
Step2: migration to Admin-Backend  successful,
Management for setting site template and extensions via backend is possible

### Actual result
1. Migration to 3.10 works fine - no errors detected
2. Migration to V4 destroyed installation
- process did not migrate to new "atum" template causing failure of admin backend  (got message "template failed")
- error500 (expected) on frontend - could not be recovered (e.g. by using template "casiopeia" for frontend) as backend failed.  

### Additional comments
Besides restoring backup of system there would be a recovery way, if at least migration of backend to V4 would be successfully.
It may ease migration to V4, if process would disable all installed extensions, where it is not ensured that they do support V4.

**Comment by dgrammatiko** [comment]
@jschmi102 The migration path was broken by https://github.com/joomla/joomla-cms/pull/30192 but fixed with https://github.com/joomla/joomla-cms/pull/30333

You need to d/l the nightly 3.10 ( https://developer.joomla.org/nightly-builds.html ) to have a successful migration

**Comment by richard67** [comment]
@dgrammatiko The update is not fixed yet. In addition to PR #30333 in J 3.10, it needs another change in J4 to remove the same statements from the J4 update scripts, otherwise the update fails, which is currently the case. But when I remove that in J4, then updating from 4.0 Beta 1 or 2 or 3 to a future Beta 4 (or nightly) fails. I've pinged @wilsonge about that for a decision what to do, but no reply yet.

**Comment by richard67** [comment]
Now, as PR #30363 has been merged, too, updates from 3.10 recent nightly or next upcoming alpha to J4 will work again beginning with the next J4 nightly.

**Comment by Quy** [comment]
https://www.joomla.org/announcements/release-news/5822-joomla-4-0-0-beta4-and-joomla-3-10-alpha2.html
