### ISSUE TITLE
[4.0] SEF don't works for urls in mod_custom

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30818]
### Steps to reproduce the issue
Upgrade from Joomla 3.6, some modules/components are not installed in 4.0

### Expected result
/2387-?layout=edit

### Actual result
/index.php?option=com_content&view=article&layout=edit&id=2387

### Additional comments
SEF links only work in the menu, article titles etc... On 100% links in `mod_custom` do not work for me. As for the articles, I'm not sure, but I have a problem that when TinyMce inserts `relative` images, these are not processed into` base () `.

I suspect that some of the extensions may not have been disabled properly. But turning on `$debug = true;` did not produce any error.

At this time I found, that in `onAfterRender` event joomla don't find URL's (`Uri:: parse($uri)` isn't called)

**Comment by brianteeman** [comment]
I had exactly the same problem. It was resolved by ensuring that the catid was in the url

@chmst looks like the same issue as with the sample data

**Comment by chmst** [comment]
In sample data,  resolved it via direct linking the menuItemId. 
Because the catid did not resolve the issue with the url. I will check again.

**Comment by brianteeman** [comment]
except that did not work - see that pr for my comments
also see that if you use the content xtd-editor plugin it will insert the link as I describe with id and catid and that works

**Comment by Hackwar** [comment]
Can you check if #42989 helps with this issue?

**Comment by Hackwar** [comment]
Since we have #42989, I'm closing this issue.
