### ISSUE TITLE
Field text float Joomla! 3.9.23 bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#31756]
### Steps to reproduce the issue

create new field type text filter float
in Field text float insert 1,5

### Expected result

1.5

### Actual result

1

### System information (as much as possible)

Joomla! 3.9.23

### Additional comments

if inserted is 1.5 you get 1.5

**Comment by drmenzelit** [comment]
Where is the "field text float"? Can you please provide more infos / screenshots?

**Comment by ghost** [comment]
drmenzelit create new field type text filter float

**Comment by drmenzelit** [comment]
I can't follow you

**Comment by ghost** [comment]
drmenzelit I can't follow you. Can you please provide more infos / screenshots how you create this field?

**Comment by drmenzelit** [comment]
Sorry, but the issue has no useful description on how to check it. If you want help, please provide a correct description.

**Comment by ghost** [comment]
Sorry drmenzelit, but the issue has all useful description on how to check it. If you want help, please create this field and provide screenshots.

**Comment by tecpromotion** [comment]
It's Christmas and I have a present for you. A screenshot :)
Please be kind to each other.

![help-screenshot](https://user-images.githubusercontent.com/1752513/102925622-05516100-4494-11eb-925a-b66ba5b42cfd.png)

**Comment by drmenzelit** [comment]
Thank you @tecpromotion :-)

**Comment by ghost** [comment]
tecpromotion thank you

**Comment by chmst** [comment]
Screenschots are wonderful. I think this is resolved now and close it

**Comment by ghost** [comment]
chmst why you closed this unfixed Field text float Joomla! 3.9.23 bug ?

Expected result

1.5

Actual result

1

**Comment by tecpromotion** [comment]
@JamesBaku I don't think this is a bug. I have looked at a few docs and assume that float values with a dot, i.e. in the form 10.45 etc., must be used.

Also, as a general note. Float is only possible in text and textarea. I did not know this before but it makes sense.

And if this is an error, you would have to look at the filter implementation if necessary, but I don't think so.

**Comment by chmst** [comment]
I think withthe screen of  @tecpromotion your problem is solved

**Comment by ghost** [comment]
the problem is realy not solved

tecpromotion solved drmenzelit problem

my issue is if user insert 1,5 he/she gets 1 as a result but should get 1.5

**Comment by tecpromotion** [comment]
@chmst @JamesBaku Not with the screenshot but possibly with my execution.
The screenshot was only helpful for understanding.
The problem is the comma instead of the point in float values.

**Comment by tecpromotion** [comment]
@JamesBaku No conversion takes place. So you will never get a 1.5 from a 1,5

**Comment by ghost** [comment]
tecpromotion yes the problem is comma instead of the point

the problem is general user do not understand or care to use comma or point

**Comment by tecpromotion** [comment]
Sorry but this is a user or training problem and not a bug in Joomla :)

**Comment by tecpromotion** [comment]
For this case, I suggest that a custom field plugin be written that covers exactly this use case.

**Comment by ghost** [comment]
tecpromotion you are right if Joomla is not user friendly and all joomla not fixed bugs are closed by chmst maybe better solution just use wordpress and there will be no need to write custom plugnis to fix joomla bugs :)

chmst please reopen this joomla issue or at least move this joomla issue to Discussions

this joomla bug issue was hijacked by drmenzelit and closed by chmst without understanding joomla issue

**Comment by chmst** [comment]
I will re-open this issue as there was a misunderstanding. Nevertheless: If users write better texts, there would be less misunderstanings. I am not in your head and do not see what you see says my son id if ask hin something.

**Comment by chmst** [comment]
Closed again. We don't accept issues from ghosts.

**Comment by N6REJ** [comment]
@HLeithner ban ghost please.  We don't need trolls.

**Comment by wojsmol** [comment]
@N6REJ @ghost is github system account used when user request his/her account deletion.
