### ISSUE TITLE
[4] Admin template broken on error pages (again) 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33741]
### Steps to reproduce the issue

To EASILY replicate, edit libraries/src/Session/SessionManager.php and put 

```php
throw new \Exception();
``` 

on line 65 in the destroySessions method, and then LOGOUT of Joomla admin to cause the crash 

### Expected result

An error displayed to the screen and the admin template to survive intact with the left bar correct. 

### Actual result

<img width="1594" alt="Screenshot 2021-05-20 at 22 03 18" src="https://user-images.githubusercontent.com/400092/119048642-6a63a100-b9b7-11eb-803c-bdef494b2a13.png">

**Comment by richard67** [comment]
I think it had the same cause as #33740 . will check later today or tomorrow morning.

**Comment by PhilETaylor** [comment]
You are confused :) haha - this issue was forked from #33740 so that the display of the admin could be fixed independently of the pgsql issue with sessions haha

**Comment by richard67** [comment]
Yes, I should go sleep soon.

**Comment by brianteeman** [comment]
As #33788 was resolved can I assume this one is as well or do I need to install postgres to check?

**Comment by PhilETaylor** [comment]
No this one is still a problem. 

To EASILY replicate, edit libraries/src/Session/SessionManager.php and put 

```php
throw new \Exception();
``` 

on line 65 in the destroySessions method, and then LOGOUT of Joomla admin to cause the crash 


<img width="1594" alt="Screenshot 2021-05-20 at 22 03 18" src="https://user-images.githubusercontent.com/400092/119048605-5ddf4880-b9b7-11eb-8aac-b8942703ab51.png">

**Comment by PhilETaylor** [comment]
I have updated the issue description

**Comment by brianteeman** [comment]
thanks - replicated it and now looking at a fix

**Comment by brianteeman** [comment]
please test #34061

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34061 . Thanks in advance.
