### ISSUE TITLE
Search Result is Stripping Characters

### ISSUE THREAD

**Issue by pnutster** [joomla/joomla-cms#34724]
### Steps to reproduce the issue
Use search to find a result containing "Mill" with double "L'

### Expected result
Result page should show "Mill" in the title with double "L"

### Actual result
The actual result shows "Mil" with only one "L"

### System information (as much as possible)
Joomla 3.9.28
PHP 7.4
MySql 5.7

### Additional comments
We have been able to locate the issue to be in the  _smartSubstr function in  /administrator/components/com_search/helpers/SearchHelper.php file

We have been able to hardcode this file to fix our issue (yes, sorry), but of-course any update to the Joomla core will wipe this out. Hopefully the stripping issue can be looked at.

I have attached an image of the site where we have encountered the issue. Showing "Mil" where it should show "Mill" - characters are being stripped.

![image](https://user-images.githubusercontent.com/4218393/124636332-cf3b6380-de5e-11eb-85f0-446cef91d99c.png)

**Further troubleshooting has made things more clear. Any title containing an apostrophe, gets the last character of the title stripped in search results.**

See attached Screenshot: 
![Screen-Shot-2021-07-06-13-48-02](https://user-images.githubusercontent.com/4218393/124638545-73260e80-de61-11eb-9c9f-fb0f701362fb.png)

Note: WE have been able to replicate the Apostrophe - Cutoff issue on a clean Joomla 3.9.28 installation:

![Screen-Shot-2021-07-06-14-12-47](https://user-images.githubusercontent.com/4218393/124640958-88506c80-de64-11eb-9cae-51d7bfb1d786.png)

**Comment by richard67** [comment]
Really 3.9.26? If so, please update to 3.9.28 and check again. IIRC this has been fixed.

**Comment by pnutster** [comment]
Thanks for checking in. Just tested on clean 3.9.28 - apostrophe search result title cutoff issue remains.

**Comment by richard67** [comment]
Thanks for reporting back.

@Hackwar Any idea?

**Comment by pnutster** [comment]
One comment that one of our programmers made:

> the smart replacement search i think filters out the appostrophe and when it rebuilds the string its 1 character shorter than it should be

**Comment by brianteeman** [comment]
This is for the original search and not finder aka smart search. It was finder that has recent bug fixes.

**Comment by richard67** [comment]
> This is for the original search and not finder aka smart search. It was finder that has recent bug fixes.

Ouch ... again I mixed that up. Thanks for the hint.

**Comment by pnutster** [comment]
Correct: the issues occur in the original search.

**Comment by ReLater** [comment]
The question for me is: Why do we strip accents here before the lengths are calculated?:
https://github.com/joomla/joomla-cms/blob/3.9.28/administrator/components/com_search/helpers/search.php#L285
and
https://github.com/joomla/joomla-cms/blob/3.9.28/administrator/components/com_search/helpers/search.php#L287

**Comment by farimas** [comment]
This is for the original search and not finder aka smart search. It was finder that has recent bug fixes[.](https://bestlivenewsonline.blogspot.com/ "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34724">issues.joomla.org/tracker/joomla-cms/34724</a>.</sub>

**Comment by farimas** [comment]
This is for the original search and not finder aka smart search. It was finder that has recent bug fixes **** https://bestlivenewsonline.blogspot.com/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34724">issues.joomla.org/tracker/joomla-cms/34724</a>.</sub>

**Comment by richard67** [comment]
@farimas We don't accept posting spam links here.

**Comment by Hackwar** [comment]
Can we move this to the com_search repository?

**Comment by zero-24** [comment]
Moving issues between orgs (joomla vs joomla-extensions) does not look like to be possible you can only move issues within on org to a different repo. I would recommend closing here and create a new issue there that links back here for history.

**Comment by richard67** [comment]
@Hackwar I just see this issue here is for 3.x where search is part of the core. Should we really move this to the search repository?

**Comment by Hackwar** [comment]
To be honest, I would consider this a wontfix for 3.x and only fix it in the 4.0 version in the standalone repo. However I don't even know what the functions/methods involved here are supposed to do. I'm not sure why we can't simply use htmlspecialchars() or something similar...

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
