### ISSUE TITLE
[3.9] [J4] [J5] No activation email is sent when admin activates user in backend

### ISSUE THREAD

**Issue by tschombes** [joomla/joomla-cms#34956]
### Steps to reproduce the issue
1. Register new user account, verify email by clicking the link in the received email.
2. As an administrator (super user), activate a new registered user account in backend.
(Setting is: Administrator has to activate new user accounts)

### Expected result
User gets email, that his account was activated and ready to use

### Actual result
User does not get a email

### System information (as much as possible)
Joomla 3.9.28
PHP 7.4
Using PHP Mail or SMTP Mail, does not matter

### Additional comments
The activation email is sent to the user, when the admin is using the activation link in the email (which he gets when a new user has registered and verified his email adress).
But when the admin is going to activate the user in the backend (instead using the link in the email), the user does not get a email notifying him, that his account is now activated and ready to use.

**Comment by brianteeman** [comment]
This is a long standing problem that for some reason never gets fixed see #20282

**Comment by tschombes** [comment]
In my opinion this should be fixed in the joomla core code, i am afraid to use a year-old patch

**Comment by brianteeman** [comment]
it should be fine - but I agree 10000% with you

**Comment by brianteeman** [comment]
This is still an issue in joomla 4 please can someone update the title and add the j4 issue label

**Comment by mgretz** [comment]
This is still an issue, any news about this?

**Comment by tschombes** [comment]
This is still an issue in J5.

Any news about this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34956">issues.joomla.org/tracker/joomla-cms/34956</a>.</sub>

**Comment by brianteeman** [comment]
Can be closed see #39650
