### ISSUE TITLE
Editor broken layout

### ISSUE THREAD

**Issue by reDimDev** [joomla/joomla-cms#35395]
### Steps to reproduce the issue
Switching the editor to code view and adjusting the scroll position of the browser, the design breaks (see attached gif below). The toolbar jumps to the left side and disappears completely when scrolling back to top. 

![screen shot 2021-08-27 at 16 06 32](https://issues.joomla.org/uploads/1/ef2621ca0f4912eaf055f5b9c2bfc45d.gif)

### Expected result
Editor doesn't break.

### Actual result
Editor breaks.

### System information
- Joomla! 4.0.2 Stable
- Mozilla Firefox 91.0.2 (64-Bit)
- PHP 7.4.22

### Additional Information
- Faulty behaviour doesn't happen in Chrome or Safari.
- Switchgin to the different toolbar modes inside the plugin config doesn't change the faulty behaviour.
- TinyMCE's sticky script for it's toolbar doesn't trigger while the editor is in it's WYSIWYG view. It does trigger on the code view, which i think shouldn't happen.
- Only workaround is to reload the page.

**Comment by dgrammatiko** [comment]
Update to latest FF version: https://github.com/joomla/joomla-cms/issues/35042#issuecomment-893688876

I mean FF 91.0.2 (MacOS) is ok

**Comment by chmst** [comment]
I have the latest FF 91.0.2 (64bit)  - on win 10 but the issue is still an issue.

**Comment by dgrammatiko** [comment]
> I have the latest FF 91.0.2 (64bit) - on win 10 but the issue is still an issue.


This is a Firefox problem, it's already solved in the MacOS version I guess the windows next version (in couple of weeks) will have the fixes as well

**Comment by chmst** [comment]
I will know it soon as I keep seeing this every day.

**Comment by dgrammatiko** [comment]
@chmst next release is scheduled for 07/09/2021.It might worth checking their nightly version to see if it's already fixed there and if not raise an issue in their bug tracker

**Comment by brianteeman** [comment]
@chmst has this been resolved with the latest versions of Firefox? If so then please can you close this.

**Comment by reDimDev** [comment]
The latest Firefox version is v94.0.1 and the issue is still around, sadly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35395">issues.joomla.org/tracker/joomla-cms/35395</a>.</sub>

**Comment by Chaosxmk** [comment]
Bug also spotted in Firefox v94.0.2, but thus far I haven't been able to reproduce in Firefox v95.0b10.

**Comment by chmst** [comment]
Not resolved.

**Comment by dgrammatiko** [comment]
Did anyone actually reported the issue to Firefox? Bugs don’t magically disappear

**Comment by Chaosxmk** [comment]
I've messed around a bit to try to find a consistent method to break the editor and see what exactly is breaking, and I'm not entirely sure this is a Joomla issue, it might be an issue more with TinyMCE. I'm not entirely sure how we're using TinyMCE so I can't say for sure though.

I can say that it looks like the editor is somehow setting parameters for itself incorrectly, but when the window is resized the editor tends to correct itself. I'm assuming that a resize tells it to just re-fetch parameters just in case different breakpoints use different parameters.

**Comment by HLeithner** [comment]
Can't replicate on windows 10 with firefox 95, please reopen if you can still replicate this.

**Comment by Chaosxmk** [comment]
Able to reproduce on Windows 10 with Firefox 95.0.2.

**Comment by dgrammatiko** [comment]
This is not a Joomla (and also not Bootstrap, tinyMCE) bug. Someone seriously needs to create a codepen with the failed behaviour and open an issue on the Firefox bug tracker (I can't I'm not on Windows PC)

**Comment by Chaosxmk** [comment]
Unfortunately, I do not know enough about how TinyMCE is used/setup to be able to replicate what's used in the backend for a CodePen demo.
