### ISSUE TITLE
Joomla exception "throw new DebugBarException("Session must be started before using stack data in the debug bar");"

### ISSUE THREAD

**Issue by morefriendm** [joomla/joomla-cms#37784]
I have updated my website to Joomla 4.13, and I'm using Postman to get data via Joomla 4 webservices. I have turned on the Debug. Now I'm getting a response to the Postman "Session must be started before using stack data in the debug bar" and it turns out /libraries/vendor/maximebf/debugbar/src/DebugBar/DebugBar.php (line 447) throw new DebugBarException("Session must be started before using stack data in the debug bar"); is executing. Can you please help me? Thanks

**Comment by chmst** [comment]
Isn't this resolved with https://github.com/joomla/joomla-cms/pull/37488?

**Comment by morefriendm** [comment]
Thanks.
Unfortunately, it did not fix the issue for me.
My environment.
   Joomla 4.1.3 on PHP 8.1.5 
    Enable debugging in the global Joomla configuration
    Set error reporting to maximum in the global Joomla configuration
    Debug plugin is enabled
It is throwing the debug bar exception "Session must be started before using stack data in the debug bar" to GET request in the Postman. Debug bar working fine on the website.

**Comment by alikon** [comment]
which endpoint are you calling via postman ?

**Comment by stell** [comment]
Same here when calling `/api/index.php/v1/content/articles`. Other endpoints also collide with session when debugging is on.
https://jsfiddle.net/fLaq7wnx/
Joomla 4.1.3

**Comment by morefriendm** [comment]
Yes, same endpoint and same response. Also, other endpoints crashing with session when debugging is on.

**Comment by Fedik** [comment]
For now disable system/debug plugin.
I will do PR for that issue.

**Comment by Fedik** [comment]
please test #37797
