### ISSUE TITLE
[5.0] After updating from 4.4.0 - Error: 0 Class "JPlugin" not found

### ISSUE THREAD

**Issue by jweaver0312** [joomla/joomla-cms#41641]
### Steps to reproduce the issue
Update from 4.3.4 to 5.0

### Expected result
No error expected
![screen shot 2023-09-07 at 18 24 32](https://issues.joomla.org/uploads/1/3fbfe9b513d88e4db9dbf3596692915a.png)

### Actual result
Error Class "JPlugin" not found

### Additional comments
PHP 8.2.5
Attaching call stack

After the update, can not sign in anymore, stuck in login loop, debugging is not yielding any results there. Same happens from 4.3.4 to 5.0.0

**Comment by jweaver0312** [comment]
Afterwords, can not sign in anymore, stuck in login loop.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41641">issues.joomla.org/tracker/joomla-cms/41641</a>.</sub>

**Comment by HLeithner** [comment]
Die you disabled all 3rd Party systrm Plugins before you Upgrades?

**Comment by HLeithner** [comment]
For the Moment you can renale the jce plugin

**Comment by richard67** [comment]
Updating to 5.0 always has to be done from the latest 4.4. direct update from 4.3.x to 5.0.0 is not supported.

E.g. the update DQL scripts from 4.4 will not be there and so not run when updating directly from 4.3.x to 5. This is currently only one update SQL script, but it might become more during the live time of 4.4.

The same applies to deleting obsolete files and folders on update. Things which would be deleted when updating from 4.3 to 4.4 before updating to 5 will not be deleted when updating directly from 4.3 to 5.

**Comment by jweaver0312** [comment]
> Die you disabled all 3rd Party systrm Plugins before you Upgrades?

With that disabled, the JPlugin error disappears, but still can not log back in after logging out of 5.0 for the 1st time.

**Comment by richard67** [comment]
Well, you can of course ignore what I wrote,  ut ignoring does not help. As I wrote, updating directly from 4.3.4 to 5 is not supported, and one of the results can be that files which would be deleted when updating via 4.4 will not be deleted.

Such files are for example the plugin files which changed their location due to restructuring plugins in 4.4. The files at the old location on 4.4 will not be deleted.

I think this then causes false results in the autoloader file when thieves generated at the end of the update, and that’s what causes your problems.

Believe me, your updated site is broken. Throw it away and start again with the 4.3.4 backup you hopefully have made before the update. Restore the backup files into an empty folder and the backup database into an empty database. Then update to 4.4.0-beta1, and then update to 5.0.0-beta1.

I promise you that rhis will work without a flaw.

For the reasons stated above I think we should close this issue as expected behavior.

**Comment by jweaver0312** [comment]
> Well, you can of course ignore what I wrote, but ignoring does not help. As I wrote, updating directly from 4.3.4 to 5 is not supported, and one of the results is that files which would be deleted when updating via 4.4 will not be deleted.
> 
> Such files are for example the plugin files which changed their location due to restructuring plugins in 4.4. The files at the old location on 4.4 will not be deleted.
> 
> I think this then causes false results in the autoloader file when that is generated at the end of the update, and that’s what causes your problems.
> 
> Believe me, your updated site is broken. Throw it away and start again with the 4.3.4 backup you hopefully have made before the update. Restore the backup files into an empty folder and the backup database into an empty database. Then update to 4.4.0-beta1, and then update to 5.0.0-beta1.
> 
> I promise you that this will work without a flaw.
> 
> For the reasons stated above I think we should close this issue as expected behavior.

Followed your steps exactly, and still same error message and issue with signing in. You broke your promise. I respond and test things in the order I see a response, you were not the 1st response, and I will not be addressing your further replies since you chose to be a jerk.

**Comment by richard67** [comment]
> since you chose to be a jerk.

@jweaver0312 But in opposite to you I was not offending someone by using swear words. You violate our code of contact.

**Comment by jweaver0312** [comment]
@richard67 "jerk" is not a swear word.

> Well, you can of course ignore what I wrote, but ignoring does not help.

Those very words you wrote were uncalled for and disrespectful. How about this, unless you have something to respectfully add to help, then do not say it.

You need to understand that I do not sit in front of a computer every second to be able to address all responses. We human beings, things happen. We get held up by other activities around.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41641">issues.joomla.org/tracker/joomla-cms/41641</a>.</sub>

**Comment by obuisard** [comment]
@jweaver0312 Insults are not tolerated, is definitely a lack of respect for the person who answered you and will definitely not get you very much help from other users or developers. @richard67 was trying to be helpful but you may have missed his first comment, so let's give it the benefit of the doubt. 

There is _no_ upgrade path from 4.3 to 5.0, any upgrade needs to go through 4.4. The installer then should get you indications on what can be a problem when moving from 4.4 to 5.0. This is a process that requires a few steps and some time for completion. Please try again.

**Comment by jweaver0312** [comment]
I tried it from 4.4 to 5.0 again and the installer did not indicate anything being a problem. I did disable JCE prior to the upgrade which cleared the JPlugin class error (so I'll safely assume there for now that that is caused by JCE that will need an update later to support 5.0). However, even with debug on, it did not fix the error or point to any issue that is causing me to be stuck on a sign in loop (not getting past the signin page) after signing out for the 1st time.

**Comment by obuisard** [comment]
The problem could come from a quickicon or a module that is not core but loads in the dashboard.

**Comment by jweaver0312** [comment]
Can you explain what you mean a bit more? Do you mean additional 3rd party stuff. The only 3rd party items to my knowledge is JCE.

**Comment by richard67** [comment]
Does JCE provide a Media Field? I've heard of cases where that made problems. Could you (just for testing on a non production copy) uninstall all JCE stuff including plugins and fields before updating from 4.3.4 to 4.4-beta1?

**Comment by obuisard** [comment]
And check the logs on your server. That's where you will get hints of what's going on.

**Comment by jweaver0312** [comment]
I uninstalled JCE from 4.3.4 prior to moving to 4.4-beta1, and then updated to 5.0-beta1, it still stays in a sign in loop after logging out.

I went to the server error logs and they are not indicating any errors.

**Comment by HLeithner** [comment]
Can you please give me access to the site? harald.leithner@community.joomla.org

**Comment by rdeutz** [comment]
@jweaver0312 calling someone a jerk is not what we want to see here. Understand this a the last warning, next time I will give you a break.

**Comment by HLeithner** [comment]
thanks I logged in but everthing is working, except front end looks odd but not sure if this is expected.

**Comment by HLeithner** [comment]
that's really strange because there are no articles in the installation, which actually can't be deleted on upgrade (at least I wouldn't believe  this).

can you please setup a j 4.4 installation with example data installed and give me access again so I can do the update my self?

**Comment by jweaver0312** [comment]
What I meant was, I initially created this installation as a direct staging clone of my production 4.3.4, deleted content, updated to 4.4 and then 5.0.

Looking through it, there's nothing really "private" or "confidential" so this time around, I will just leave everything intact when I rebuild the clone (minus JCE of course) and I'll remove the Custom CSS.

**Comment by HLeithner** [comment]
you can keep jce and custom css. the upgrade should work as it is, only disabling of system plugins is needed.

**Comment by jweaver0312** [comment]
I just tested it again myself, keeping everything and just left JCE in a disabled state on 5.0, and the login issue replicated. Let me just delete it again and rebuild it so I can put it on 4.4 for you.

**Comment by jweaver0312** [comment]
@HLeithner it is all set on 4.4, same URL, same credentials for you to use.

**Comment by HLeithner** [comment]
@jweaver0312 I did the update, everything went well without data loss,,, I keeped jce deactivated so I see no problem (except the server need a really long time for upgrading but I think that's not relevant here)

**Comment by jweaver0312** [comment]
I just tried to log in after you and its stuck in a login loop again.

**Comment by jweaver0312** [comment]
It now appears to be a caching issue for the browser after updating to 5.0, that the browser needs to be cleared of history/cache/cookies, before logging in after, weirdly that does not happen during the 4.4 update.

**Comment by thodorisgo** [comment]
I faced this issue after upgrading from 4.4.3 to 5 and i fixed it by dissabling akeeba backup from my database.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41641">issues.joomla.org/tracker/joomla-cms/41641</a>.</sub>

**Comment by Lumiga** [comment]
@thodorisgo that didn't fix the issue for me. Hopefully someone else will find a solution form me.

**Comment by Kupers** [comment]
0 Class "JPlugin" not found
I got this too
4.2.5-4.4.3-5.0.3
I installed a clean version 4.4.3, installed plugins from the old version, updated them to the current one with support for 5
updated to 5.0.3 and everything works
if I update in this order 4.2.5-4.4.3 installed plugins from the old version-5.0.3
then I get an error

**Comment by HLeithner** [comment]
One of your installed plugins are outdated so we need the b/c plugin which should be activated automatically when you install 4.4.x. can you confirm that this is activate?

Also for upgrade disable all 3rd party system plugins.

**Comment by ssnobben** [comment]
I also have this problem and wonder after an update to J 5.1 how to solve to remove this issue? I cant have the compability plg off then I get stucked in Joomla backend and have to enable it in the db to get it work again..

**Comment by chmst** [comment]
Enable the plugin in the database. 
As long as you are using extensions which are not ready for J5 you need the compatibility plugin.
