### ISSUE TITLE
Fontawesome 5 error randomly on j5

### ISSUE THREAD

**Issue by trananhmanh89** [joomla/joomla-cms#42611]
### Steps to reproduce the issue
I can't tell, because it happens randomly, and it's gone after several refreshes.

### Expected result
Fontawesome should show fine.

### Actual result
Check the image

![image](https://github.com/joomla/joomla-cms/assets/20571336/a3f52d88-d54d-4258-9bb2-160bb49fbc06)

### System information (as much as possible)
chrome browser
windows 11
cpu intel i5-8400
nvidia card 1050ti
php82
mysql 80
apache 2.4.52

### Additional comments
Does anyone have this issue?

**Comment by joeforjoomla** [comment]
Confirmed. It happens to me too. After clearing the browser cache and reloading the page, everything is back to normal.

**Comment by fgsw** [comment]
> Does anyone have this issue?

Using Joomla5 since 2 month never happened.

**Comment by brianteeman** [comment]
It happens to me quite often as well. Thought it was just me but obviously not

**Comment by richard67** [comment]
Does the network tab of the browser's developer tools show something when this happens, or does the browser's error console?

**Comment by richard67** [comment]
@brianteeman Is it also with the Chrome browser in your case? Or also with other browsers?

**Comment by trananhmanh89** [comment]
> @brianteeman Is it also with the Chrome browser in your case? Or also with other browsers?

My colleagues are using firefox and do not face this issue till j5 update. Thought might because chrome and nvidia graphic card.

**Comment by brianteeman** [comment]
> @brianteeman Is it also with the Chrome browser in your case? Or also with other browsers?

I only use Chrome on Windows

**Comment by richard67** [comment]
Does it also happen with Joomla 4.4.x? Or only with 5?

**Comment by joeforjoomla** [comment]
It seems just in J5

**Comment by joeforjoomla** [comment]
UPDATE: it also happens on J4

**Comment by ssnobben** [comment]
Do you have any conflicting Fontawesome installed before updating?

**Comment by chmst** [comment]
I cannot replicate - win11 with different browsers but always correct icons. A conflict with former versions could explain the effect

**Comment by brianteeman** [comment]
Completely clean install just now on localhost of current 5.1git.

No console errors and as soon as you hit refresh it works

![image](https://github.com/joomla/joomla-cms/assets/1296369/8c4505da-dd18-47d3-b876-a048a2db06a1)

**Comment by richard67** [comment]
Maybe the issue is somehow related to the [font-display](https://www.w3docs.com/learn-css/font-display.html) CSS property? Maybe it has something to do with optimizations with Chrome version 83 for handling "font-display: optional" which are mentioned on this page https://web.dev/articles/preload-optional-fonts?hl=en and more detailed handled here: https://bugs.chromium.org/p/chromium/issues/detail?id=1040632 ?

**Comment by richard67** [comment]
Unfortunately I can't reproduce it here.

**Comment by brianteeman** [comment]
I can't reproduce it on demand either. Although lats night I did see it twice on a site that was not one of my own. The link you shared about font-display does sound similar

**Comment by Fedik** [comment]
I cannot reproduce it,
However I suspect it may also be related to file loading or server response. Because of:

> ... and as soon as you hit refresh it works

That sounds like the initial load went wrong, and cached version works.

Try disable cache:
- Open Dev Tools Network tab
- Check "Disable cache" checkbox
- Reload the page. Now every reload will be without cache.

Do you able to reproduce it every time now?
Addittinaly try "Network throttling".

If you able to reproduce then also please look for a response headers `for fa-solid-900.woff2` does it `font/woff2` or something else?

**Comment by brianteeman** [comment]
I just observed this on a developers website
![image](https://github.com/joomla/joomla-cms/assets/1296369/eb0b6176-e03b-40ae-86e3-221673bfc7f3)

When I checked with chrome inspector it did show the woff2 files as loaded
It did NOT show joomla-fontawesome.min.css as loaded
It did not show any errors

**Comment by trananhmanh89** [comment]
when the icon get error, chrome didn't load any css from joomla

![image](https://github.com/joomla/joomla-cms/assets/20571336/bb165c5f-cd06-4036-b59d-d680206704b9)

And this is when no icon issue

![image](https://github.com/joomla/joomla-cms/assets/20571336/02c2cd9c-e6bd-45ab-a0e0-bb5d9be5e832)

fact: open new tab with same url, the issue will gone

**Comment by brianteeman** [comment]
I strongly suspect that this is caused by something related to https://github.com/joomla/joomla-cms/pull/32141

// Defer fontawesome for increased performance. Once the page is loaded javascript changes it to a stylesheet.

**Comment by richard67** [comment]
> I strongly suspect that this is caused by something related to #32141
> 
> // Defer fontawesome for increased performance. Once the page is loaded javascript changes it to a stylesheet.

@brianteeman Yes, I have the same thing in mind. On my private website I have disabled that lazy loading of the fonteawesome fonts in my child template.

**Comment by Fedik** [comment]
Nope, that PR affecting only frontend, and the issue about admin side.

**Comment by trananhmanh89** [comment]
Update: chrome on ubuntu also got this issue.

**Comment by dgrammatiko** [comment]
It’s either:
- the server (mime types, etc)
- Some plugin doing something stupid

**Comment by Fedik** [comment]
Another thing I would probably try is to use the `preload` header for the fonts for admin.
In j4 FA fonts files size ~160kb
in j5 FA font files size ~260kb

**Comment by dgrammatiko** [comment]
At the time we were doing those optimizations preload wasn’t supported across the board but now should be done, no questions asked

**Comment by brianteeman** [comment]
> It’s either:
> 
> * the server (mime types, etc)
> * Some plugin doing something stupid
> * Wrong CSP configuration

At least in my case I have observed this with clean joomla installs so that would rule out the plugin or csp and if it works on reload it cant be the mime types

**Comment by Fedik** [comment]
@brianteeman can you please try to test following code? it adds a font 'preload' header. Place it somewhere in index.php of the admin template.
```php
$pm = $this->getPreloadManager();
$pm->preload(Uri::root(true) . '/media/vendor/fontawesome-free/webfonts/fa-brands-400.woff2', ['as' => 'font', 'type' => 'font/woff2', 'crossorigin' => 'anonymous']);
$pm->preload(Uri::root(true) . '/media/vendor/fontawesome-free/webfonts/fa-solid-900.woff2', ['as' => 'font', 'type' => 'font/woff2', 'crossorigin' => 'anonymous']);

```

**Comment by dgrammatiko** [comment]
@Fedik this `Uri::root(true) . '/media/vendor/fontawesome-free/webfonts/fa-brands-400.woff2'` won't actually work as expected because the URL of the font is versioned in J5 (ends with something like `?954876`) which means that the preloaded font will not be the same as the one specified in the css, basically the browser will download the fonts twice (there will be a warning also in the console). The actual URL could be picked in the build time of the packages before the release (doing it at run time is not a good idea)

**Comment by dgrammatiko** [comment]
@brianteeman do you get this if your browser has disabled all the extensions (or in incognito mode). There a very good chance that some of your chrome extensions is misbehaving...

**Comment by brianteeman** [comment]
@dgrammatiko its random and not reproducable unfortunately but clearly effecting multiple people

**Comment by Fedik** [comment]
@dgrammatiko it will work, because its is not versioned, I have tested on my test server, and the font loaded only once with preload tag. 
But I do not have the reported issue, so can't say if it fix anything. Someone who have this issue should do testing.

**Comment by brianteeman** [comment]
@fedik loading the font is not the problem https://github.com/joomla/joomla-cms/issues/42611#issuecomment-1885120401

**Comment by Fedik** [comment]
it is diferent, it about pre-loading not just loading

**Comment by dgrammatiko** [comment]
> it is diferent, it about pre-loading not just loading

@Fedik this guy [in this comment](https://github.com/joomla/joomla-cms/issues/42611#issuecomment-1885120401) did NOT had the (or any) css file loaded, so the problem is probably different (ie browser extension/server problem)

**Comment by brianteeman** [comment]
s

> it is diferent, it about pre-loading not just loading

That will still be nothing to do with the css which is where the problem is

**Comment by Fedik** [comment]
> did NOT had the (or any) css file loaded

> he css which is where the problem is

There no problem with CSS, I suspect it is a misuse of dev tools, 
it does not show anything useful when you open it after page is loaded

**Comment by dgrammatiko** [comment]
FWIW the installable package for 5.0.2 for both the fontawesome.[min.]css files doesn't have any entry for the path of the font. That combined with other css related breaks I think point out that switching postcss to lightningcss probably was not tested enough. Someone needs to confirm that the font `url()` is actually missing and then someone needs to figure out why, etc

**Comment by brianteeman** [comment]
> it does not show anything useful when you open it after page is loaded

Who said it was opened after page load

**Comment by Fedik** [comment]
> Who said it was opened after page load

Me. Look at the screenshots, also without any css whole site would be broken.

**Comment by trananhmanh89** [comment]
When an icon error occurs, the fontawesome.css is loaded from the template "atum," not from Joomla media. Additionally, the icon content appears abnormal.

![image](https://github.com/joomla/joomla-cms/assets/20571336/8fcd9b8a-eba9-4e34-b36e-5cf0c818d22c)

Upon examining the original fontawesome.css from the "atum" template, it is evident that the icon content is also irregular.

![image](https://github.com/joomla/joomla-cms/assets/20571336/aa491ba3-166c-45c2-b841-7c47e62a182c)

This differs significantly from the fontawesome.css found in Joomla media or the FontAwesome GitHub repository.

![image](https://github.com/joomla/joomla-cms/assets/20571336/351404e3-1362-4587-9897-8a4941a7e582)

**Comment by Fedik** [comment]
Can someone please test, if update Fontawesome to newest version helps https://github.com/joomla/joomla-cms/pull/42721
Thanks.

**Comment by Fedik** [comment]
For reference:
- https://github.com/FortAwesome/Font-Awesome/issues/10842
- https://github.com/sass/libsass/issues/1235

**Comment by Fedik** [comment]
Please try following, edit Fontawesome css, manualy and place:
```css
@charset "utf-8";
```
at top of each file .css and .min.css:
```
media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.css
media/templates/administrator/atum/css/vendor/fontawesome-free/fontawesome.min.css
```

it looks like Browser get confused with content encoding, randomly.

**Comment by dgrammatiko** [comment]
@Fedik what's unfortunate here is that when we had Postcss, the `@charset` was always appended...

**Comment by Fedik** [comment]
@dgrammatiko it more about sass compiler, this potato removes `@cahrset` when detect UTF8, even with `charset: true`.
Only way I see is to prepend it manualy

**Comment by trananhmanh89** [comment]
> @dgrammatiko it more about sass compiler (or probably both sass and lightning css), this potato removes `@charset` when detect UTF8, even with `charset: true`. Only way I see is to prepend it manualy

Hi,
I've compiled font awesome of atum template by using dart-sass, and result very different. Could you check?
The left is mine, the right is from joomla
![image](https://github.com/joomla/joomla-cms/assets/20571336/948ecd0a-f540-4c3a-b975-cb8000ba419a)

**Comment by Fedik** [comment]
Your with escaped symbols, and joomla with non-escaped.
Techicaly both should work the same, but somehow non-escaped seems not always as good as should.

**Comment by trananhmanh89** [comment]
> Isn’t sass and dart-sass the same package?

If you use this command to install sass 

`npm install -g sass` 

so it's dart-sass.

https://www.npmjs.com/package/sass

**Comment by Fedik** [comment]
Btw, we use `sass-embedded` wich is `dart-sass`, version 1.67

**Comment by trananhmanh89** [comment]
> Btw, we use `sass-embedded` wich is `dart-sass`, version 1.67

I noticed that in the package.json file, but I'm not sure why my compiled CSS is significantly different from Joomla's.

**Comment by Fedik** [comment]
Okay, it clearly sass and browser issue. 
Sass (dart-sass) stopped escaping non ASCII symbols, and the Browser may interpret the file with this symbols incorrectly (due to network or enabled gzip/deflate on server), unlles the file have defined `@charset 'utf-8'` (which sass also deleting successfully)

Another links:
- https://github.com/sass/dart-sass/issues/568 (issue from 2019)
- https://stackoverflow.com/questions/25488037/sass-compile-fontawesome-preserve-notation

@trananhmanh89 what version of sass did you use?

**Comment by Fedik** [comment]
Sorry, it is not Scss (it works fine, and keep the icons escaped) (I have edited my previous comment)
It is LightningCSS which is "trashing" everything :)

**Comment by dgrammatiko** [comment]
Possible fix: https://github.com/joomla/joomla-cms/pull/42938

**Comment by Quy** [comment]
I am going to assume this is fixed with #42938. If not, this can be reopened. Thanks for the report.

**Comment by trananhmanh89** [comment]
> I am going to assume this is fixed with #42938. If not, this can be reopened. Thanks for the report.

No, it's not resolved yet. Please do not use raw utf8 for fontawesome.

![image](https://github.com/joomla/joomla-cms/assets/20571336/be41c0df-438a-4474-b8ba-f24d606a6b2f)

**Comment by Fedik** [comment]
> No, it's not resolved yet.

@trananhmanh89 how did you tested it? (recent changes)
The fix only will be in upcoming 4.4.4 and 5.1 release.

Also, do not trust what browser dev tool shows you, it is not able to render every simbol in dev console.

**Comment by Fedik** [comment]
I just wanted to be sure whether you tested on dev branch of 5.1-dev or not.

> I thought the solution would be using escaped utf8 

It one of possible solutions. 
Another one is to prepend encoding to the CSS file, that what was done in #42938

So if you able to test on latest 5.1 RC, that would be nice.
https://github.com/joomla/joomla-cms/releases/tag/5.1.0-rc1

**Comment by trananhmanh89** [comment]
Ok, I asume that adding `@charset` rule could fix the icon error. But why I don't see `@charset` rule in file `fontawesome.css` of atum template?

Checked on package Joomla_5.1.0-rc1-Release_Candidate-Full_Package.zip

**Comment by bembelimen** [comment]
This is an issue of the build script, three persons tested now with a clean and fresh checkout. If we run normal npm install, it's included, if we do a ```php build/build.php``` the charset is not included.

So the build script is broken and the mentioned fix did not fix it.

**Comment by dgrammatiko** [comment]
This can be close since https://github.com/joomla/joomla-cms/pull/43207 is merged
