### ISSUE TITLE
[4.3] [PHP 8.1] Fixes Deprecated: strtolower(): Passing null to string in libraries\vendor\joomla\filter\src\InputFilter.php on line 213

### ISSUE THREAD

**Issue by makaveli1563** [joomla/joomla-cms#42836]
Fixes Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in  libraries\vendor\joomla\filter\src\InputFilter.php on line 213

The identical error was here: https://github.com/joomla/joomla-cms/pull/37009

**Comment by chmst** [comment]
Thank you for reporting.

Could you describe what you did to get this warning?

https://github.com/joomla/joomla-cms/pull/37009 was another piece of code.

**Comment by makaveli1563** [comment]
I am using the com_jevents component in which the Clean() method is called.
The file path is: components\com_jevents\libraries\gwejson_findcreator.php
Line: 63
The code responsible for the call: $title = InputFilter::getInstance()->clean($requestObject->typeahead, "string");

**Comment by ReLater** [comment]
"My" `gwejson_findcreator.php` uses library

`use Joomla\CMS\Filter\InputFilter;`

which is file `libraries\src\Filter\InputFilter.php`

But in your first post you say it's file `libraries\vendor\joomla\filter\src\InputFilter.php` (`use Joomla\Filter\InputFilter;`)

Could you please check which `use` line is used in "your" `gwejson_findcreator.php`

**Comment by makaveli1563** [comment]
`use Joomla\CMS\Filter\InputFilter; `

**Comment by makaveli1563** [comment]
The library and the component as a whole uses Joomla\CMS\Filter\InputFilter, but an error on the site leads to the file libraries\vendor\joomla\filter\src\InputFilter.php , which is called as: Joomla\Filter\InputFilter.

I tried changing it to Joomla\Filter\InputFilter, but it didn't give much result.

InputFilter accesses the clean method and there I tried to pass the type (string) to the parameters, which also did not give results.

**Comment by Hackwar** [comment]
I'm sorry, but you are saying that you are using Joomla 4.3. Please update to at least Joomla 4.4. We don't support 4.3 anymore. To be honest, if this is an issue on Joomlas side, there is a very big chance that we fixed it in 4.4 already and otherwise you have to contact the developer of the extension to fix this. Please report back when you still encounter this issue on 4.4. If that is the case, we can open this issue again, but for now I'm closing this.

**Comment by makaveli1563** [comment]
I updated the joomla version to 4.4.3 and my error remained.
We fix it like this on line 213
$type = ucfirst(strtolower($type));
**$type = ucfirst(strtolower((string) $type));** 
like here: #37009
