### ISSUE TITLE
[5.1] Problem with encoding in pop-up

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#43013]
### Steps to reproduce the issue
Install a nightly build + several languages that use encodings other than en-GB. For example - Russian, Ukrainian, Belarusian languages (utf-8). Accordingly, set the language for the admin panel from these languages.

Go to plugins and disable, for example: **Content - Smart Search**, **System - Redirect**.

Go one by one to the smart search and redirect components. You will see a notification about disabled plugins. Click on the link, there is a rebus in the title.

![Screenshot_11](https://github.com/joomla/joomla-cms/assets/8440661/12119bf6-bc3b-4005-b3dc-4ec7d6d95079)

This is probably due to the PR for modal pop-ups, because I have already found problems with “recognizing” the HTML code for special characters in pop-ups.

![Screenshot_2](https://github.com/joomla/joomla-cms/assets/8440661/e8015188-23f3-404e-8c52-ea995d92bf95)

**Comment by brianteeman** [comment]
I assume this has been fixed elsewhere as I cannot replicate the reported problem

![image](https://github.com/user-attachments/assets/8bdb40c9-a389-4932-a4ec-85f9ca899911)

![image](https://github.com/user-attachments/assets/8390b15b-ec6f-457a-8e0a-ce124c0d363c)

**Comment by Kostelano** [comment]
> I assume this has been fixed elsewhere as I cannot replicate the reported problem
> 
Here we have actually fixed it, since the problem was left unattended - the "arrow" has been replaced with a word.

In other windows the problem still exists. There the language is simply in the UTF-8 encoding (see the 1st screenshot).

**Comment by brianteeman** [comment]
what arrow ???

![image](https://github.com/user-attachments/assets/5065b11a-f218-44e7-b00a-9756ebb9ca8d)

**Comment by Kostelano** [comment]
> what arrow ???
> 
It doesn't matter, it was in our language before.

As for the problem, you can add a Cyrillic letter to the `COM_REDIRECT_EDIT_PLUGIN_SETTINGS` line of the en-GB language, save in UTF-8 and go to **System - Redirects**, click on the **Redirect System Plugin** link.

![Screenshot_1](https://github.com/user-attachments/assets/bbe4791c-cc4a-46c0-9570-bfc3ac887e7a)

**Comment by Fedik** [comment]
About the arrow, you should use simple text, just replace `&#8594;` with real arrow simbol (the HTML is not allowed anymore :smiley: ): https://github.com/joomla/joomla-cms/blob/481a5d6f9fa65b3adad3d32b57e7d96a6c4e0c0d/build/media_source/plg_system_shortcut/js/shortcut.es6.js#L149

About the plugin editing, I can confirm the issue.

**Comment by Fedik** [comment]
The problem comes from `$app->enqueueMessage()` https://github.com/joomla/joomla-cms/blob/a7f5e500072575fd9cf4974926d44a38b7fec88b/libraries/src/Application/CMSApplication.php#L247-L250

Which doing extra filtering and destroys UTF-8 encoded symbols

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/43874
