### ISSUE TITLE
[5.1.0]: Manage Extensions new buttons create misalignment of buttons on the 2nd row

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#43030]
### Steps to reproduce the issue
Login to backend, go to System -> Manage -> Extensions... Look at the buttons which now come on 2 lines due to the addition of the new buttons: Install Extensions / Check For Updates / Clean Cache 

### Expected result
IF there is to be a second line of icons, then they should be left align and not offset.

### Actual result
There is a spill over to a 2nd line and there is a offset for the 2nd line :/

### System information (as much as possible)
Macbook Pro Intel i9 / Safari version 17.3.1 (19617.2.4.11.12)
MySQL version | 8.0.36
PHP version | 8.2.16

### Additional comments
The Clean Cache button should be in the top bar as it is a very useful and very often used function... since it isn't yet in Joomla core, I install RegularLabs cache cleaner on all sites... :/  but this would solve both situations, 1. have a very used function accessible EVERYwhere 2. have 1 less button on this toolbar which would make it fall onto 1 line again.

![screenshot_2443](https://github.com/joomla/joomla-cms/assets/2597232/08654d9c-3968-4358-a75d-51f5d3d92b71)

(For clarity, in the image above, the Clean Cache button in the top line on the right is RegularLabs Clean Cache plugin).

**Comment by brianteeman** [comment]
Please test #43112

**Comment by LadySolveig** [comment]
I would be very happy about a test of this possible solution @exlemor. Thank you in advance

**Comment by alikon** [comment]
fixed by #43146

**Comment by brianteeman** [comment]
it is not fixed. that addressed one view. there will be still be issues in both core and extensions using the toolbar

**Comment by alikon** [comment]
the view reported on the issue imho
