### ISSUE TITLE
J 5.1.1RC not updating the version number on install 

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#43507]
### Steps to reproduce the issue
Install the RC over Joomla 5.1 (Using Joomla update)

### Expected result
Version number should be updated to show the current build

### Actual result
Version says 5.1.0

**Comment by chmst** [comment]
Version 5.1.0 is ok. The message for RC was a small bug and is fixed now, we are still on 5.1.0.

**Comment by Stevec4** [comment]
It should atleast say 5.1.1 or why even have it as a download? I just installed it 5 minutes ago so it is not fixed. Using the download Zip files is fixed.
