### ISSUE TITLE
Admin password doesn't validate and yet it goes through and then the installator crashes

### ISSUE THREAD

**Issue by Milo-W** [joomla/joomla-cms#46111]
### Steps to reproduce the issue
1. Try to install Joomla 5.3.3.
2. At the "give admin info" page add stuff, add wrong password specs, like not complicated enough (or character length). It shows a grey message which is not really visible.
3. It lets you go through. You add the database info, etc.
4. It gets blocked with a screen without possibility to come back saying the admin password doesn't meet validation.

### Expected result
It shouldn't allow going further from the "give admin details" when the password doesn't meet validation rules.

### Actual result
Goes through, blocks later, without possibility to come back.

### System information (as much as possible)
Normal environment, Joomla 5 installed with 5.2.x or something was allright. Don't remember.

### Additional comments
Might be 5.3.3 characteristic.

**Comment by chmst** [comment]
@brianteeman I cannot find the issue. But recently thought that any error should go back to top. Was there a reason why we don't do that?

**Comment by alikon** [comment]
please test #46173

**Comment by Milo-W** [comment]
> > It gets blocked with a screen without possibility to come back saying the admin password doesn't meet validation.
> 
> [@Milo-W](https://github.com/Milo-W) You can't use the back button (arrow left) of your browser to go back?

Nope, it goes all the way to the previous page, not even this exact installation process.
Besides, good UX says to validate "here & now", not two screens later...

**Comment by Milo-W** [comment]
> [@chmst](https://github.com/chmst) there are other issues about this. I think one was from [@HLeithner](https://github.com/HLeithner) If you ignore the warning about a weak password and continue the rest of the installation steps then you end up with this page
> 
> <img alt="Image" width="745" height="518" src="https://private-user-images.githubusercontent.com/1296369/490989426-fc142017-7638-4948-a9d3-762fccc94cd5.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA3MDAxMTQsIm5iZiI6MTc2MDY5OTgxNCwicGF0aCI6Ii8xMjk2MzY5LzQ5MDk4OTQyNi1mYzE0MjAxNy03NjM4LTQ5NDgtYTlkMy03NjJmY2NjOTRjZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMTdUMTExNjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzVhNGI4NWU0NTM0MjA3MDk3YTQyZjkyYThkMDM2ZjRkZTdlZDZhZmYzMWUzMjFjNDhlZTllNjhjYjc5YzU0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ULt5F0HDWuftvfH4JRDW33VgjjojdrZLM602jMPNRGw">

Yes, part of my problem here is this page here. And you go back - it goes back not even to the beginning of the process but it goes back to the previous page you had visited...

**Comment by richard67** [comment]
@Milo-W Please test PR #46173 and report back results there. Thanks in advance.

**Comment by Milo-W** [comment]
BTW it's the same in Joomla 6...
- lets go through with easy password
- no navigation back
- validates later on and no way to go back

**Comment by Milo-W** [comment]
You mean 5.5?
OK because I tested 5.4 and it didn't work better.

OK, downloading 5.4-dev.

**Comment by richard67** [comment]
5.4. There will never be a 5.5. And you have to test the pull request which I have mentioned.

**Comment by Milo-W** [comment]
Oh, 5.4-dev needs local environment...  I'm not that far with all that : /

Can test 5.4 alfa/beta though...

I hope the change is not only about the characters check but also earlier validation...

**Comment by richard67** [comment]
5.4 Alpha or beta will not contain the fix from the PR. We have already released 5.4.0 stable. You can test the PR as described here: https://docs.joomla.org/Testing_Joomla!_patches/en#Prebuild_packages

**Comment by Milo-W** [comment]
Because you said:
"So it does not need to make a new issue for 6.0, it just needs to test that PR to come forward."
and I want to make sure it's OK in 6.1 as this issue is still present in 6.0.

Sorry but this is new to me, I don't know what it means to test a PR ; ) it means to make changes in the individual files?
To be honest, #46173 looks like just the characters thing but does it not allow going forward with installation if the password doesn't meet validation rules? Because another problem was you could go forward and then it didn't allow to go further on and yet you couldn't go back. So I see at least 2 mechanics here to be made up for.
