### ISSUE TITLE
[J 5.4] The logged in users module on the backend side doesn't work properly.

### ISSUE THREAD

**Issue by Teo-Mo80** [joomla/joomla-cms#46394]
### Steps to reproduce the issue
In the session manager settings, set the database and session lifetime to 60. The session closes normally. The problem is that on the Joomla administration side, the logged in users module continues to track expired sessions. I've been experiencing this problem since Joomla version 5.4. This didn't happen in previous versions.

![Image](https://github.com/user-attachments/assets/90bb85b3-46bb-441c-be37-71f1a683d514)

![Image](https://github.com/user-attachments/assets/225eba15-d40c-4dcf-b579-c7b54c49e26e)

### Expected result

Closed user sessions should not appear

### Actual result

Expired user sessions remain visible in the form

### System information (as much as possible)
Joomla 5.4

**Comment by alikon** [comment]
if you set and enable the SessionGC task plugin with the same session time, should solve  your issue i guess
can you try and report back ?

**Comment by Teo-Mo80** [comment]
@alikon, The sessiongc plugin is enabled and set up as you intended, I think. I can't figure out how to set the session duration because there isn't the dedicated field.

![Image](https://github.com/user-attachments/assets/d80c7355-3875-4a43-9c54-a8ebf3ca4be9)

![Image](https://github.com/user-attachments/assets/16e9915e-7a21-4fff-a0c9-2ae64679591e)

**Comment by alikon** [comment]
if you were scheduling via CRON there was an error in the SessionGC task plugin, now fixed with https://github.com/joomla/joomla-cms/pull/46128

**Comment by Teo-Mo80** [comment]
> se stavi pianificando tramite CRON c'era un errore nel plugin delle attività SessionGC, ora risolto con [#46128](https://github.com/joomla/joomla-cms/pull/46128)

Hi, how can I fix this in a test environment to see if it works?

**Comment by Teo-Mo80** [comment]
I updated to Joomla 5.4.1, but it still doesn't work. I tried running the test manually via scheduled tasks, but it doesn't delete old sessions. Should I try forcing each user to log out and see if new sessions work properly?
