### ISSUE TITLE
If we logged out from front end then multiple validation message is displayed.

### ISSUE THREAD

**Issue by amithadkar** [joomla/joomla-cms#4784]
#### Steps to reproduce the issue
1. **In User Manager options make sure that Frontend User Parameters is set to hide**
2. Open front end of joomla.
3. Login using admin with valid credentials.
4. Click on logout button.
5. Verify the results.

#### Expected result
Only one validation message is displayed

#### Actual result
Validation message is displayed twice.

#### System information (as much as possible)
PHP Built On Windows NT 6.2 build 9200
Database Version 5.6.12-log
Database Collation utf8_general_ci
PHP Version 5.4.12
Web Server Apache/2.4.4 (Win64) PHP/5.4.12
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.3.7-dev Development [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Windows NT 6.1; rv:32.0) Gecko/20100101 Firefox/32.0

![screen shot 2014-10-17 at 08 49 41](http://issues.joomla.org/uploads/1/0ec339c9b23e60ef23b4ae9da9657456.png)#### Additional comments

**Comment by ChuckNorrison** [comment]
I got the same issue. Frontend User Parameters are hidden in my setup.

**Comment by FPerisa** [comment]
I tested the problem with Joomla 3.4.4-dev and I got the error message "Please log in first" only once not twice. It doesnt matter if the Frontend User Parameters is set on "show" or "hide". Maybe it was fixed with the update?
Should the redirect to the original page get fixed nevertheless?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4784">issues.joomla.org/joomla-cms/4784</a>.</sub>

**Comment by ChuckNorrison** [comment]
in this case the multiple validation message is fixed. I got this in some other situations i cant reproduce...

**Comment by amithadkar** [comment]
Issue is still exist.
Steps to reproduce are already as stated above.

**Comment by pe7er** [comment]
This is a known issue with a Joomla installation using the brochure sample data. As it seems specifically related to the brochure sample data, and the sample data is being reviewed by PLT, I'm closing this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4784">issues.joomla.org/joomla-cms/4784</a>.</sub>

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4784">issues.joomla.org/joomla-cms/4784</a>

**Comment by amithadkar** [comment]
@pe7er Kindly provide the appropriate patch and then close this issue else reopen it.

@zero-24 Please reopen this issue.

@brianteeman Kindly look into this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4784">issues.joomla.org/joomla-cms/4784</a>.</sub>

**Comment by amithadkar** [comment]
@brianteeman  Can you please give me update?

**Comment by zero-24** [comment]
I can not reproduce this on 3.7.0-dev also with the `brochure sample data`

**Comment by amithadkar** [comment]
@zero-24 I have tested on joomla 3.6.2 and it is fixed.

**Comment by zero-24** [comment]
Thanks for the feedback :+1:
