### ISSUE TITLE
REGRESSION: Language selection is not "remembered" when returning to site

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#6213]
read: http://forum.joomla.org/viewtopic.php?f=711&t=874852&p=3272103#p3272103

I did a quick test.

When selecting a language (en), cookie is set in path /en/ with value "en-GB" expiration this date next year.

When returning to the site, the language shown is dutch (nl).. Not even by choice of language default as "en" is set as default.

**Comment by engelweb** [comment]
I believe we're experiencing the same issue with our site; Joomla 3.4 seems to default to system language/browser language (depending on the setting of the language filter), completly ignoring the stored value in the cookie.

We noticed becuase it affects all SEF URL's not containing a language segment on our site.
Any URL like "example.com/pages" missing the language (ex. /en/) will automatically redirect to the default of the filter now, rather than checking with the cookie to retrive the current language.

**Comment by pekollik** [comment]
I am running Joomla! 3.4.0 at localhost and I was not able to reproduce the issue. I installed dutch language packet, changed default  language both for Site and Administrator back and forth between Encouple of time and everything was ok.

**Comment by pieter-groeneweg** [comment]
Aha, yes indeed... it listens to the browser preference...

...but NOT to the cookie....

**Comment by infograf768** [comment]
I confirm the regression.
The cookie is saved indeed, but when we load the url without languagecode it does not redirect to the last language used but to the default site language, whatver the settings for a new visitor (which the user is not, as a cookie exists).
this happens when "Remove URL Language Code" is set to Yes

**Comment by Hackwar** [comment]
@engelweb What you are describing is expected behavior. The cookie should never change the URL, but only hint which language you want. Since we don't want duplicate content, you can only remove the language code from the URL for the default language of the site, not of the specific user.

**Comment by infograf768** [comment]
@Hacwar
what I describe is unwanted behaviour.
The cookie should be used, even when "Remove URL Language Code" is set to Yes

**Comment by davdebcom** [comment]
There is no discussion possible about whether it should work this way or not, because it used to work this way. It is a backwards compatibility issue that needs to be fixed, because the project decided that in the 3.x upgrades there would be no BC incompatible changes. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6213">issues.joomla.org/joomla-cms/6213</a>.</sub>

**Comment by brianteeman** [comment]
Agreed - this is a B/C change that needs to be fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6213">issues.joomla.org/joomla-cms/6213</a>.</sub>

**Comment by Hackwar** [comment]
I don't see anybody denying that. I simply said that the behavior that @engelweb!! experiences is the expected behavior. Or does anybody claim that it would be ok to get dutch or english content under the exact same URL simply based on a cookie?

**Comment by HermanPeeren** [comment]
When english is the default language, but the cookie says dutch was last used, then the url should be redirected to the dutch url.

Now https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L241-L247 just take the default site language without looking at the cookie.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6213">issues.joomla.org/joomla-cms/6213</a>.</sub>

**Comment by davdebcom** [comment]
Exactly, what @HermanPeeren says. 
```When english is the default language, but the cookie says dutch was last used, then the url should be redirected to the dutch url.```

Of course with a correct redirect, not 301 but 303?

**Comment by Bakual** [comment]
Closing this since Hannes did a PR #6230.
Please test so we can fix this in staging. Thanks all!

**Comment by HermanPeeren** [comment]
This should be reopened as #6230 is closed now and this issue not yet solved. Working on a PR.

**Comment by Bakual** [comment]
Agreed

**Comment by infograf768** [comment]
Found another issue:
http://forum.joomla.org/viewtopic.php?f=711&t=875100

Folks, I wonder now if we should not simply revert the original PR.

**Comment by engelweb** [comment]
Sorry for this late reply, but I forgot a detail in my previous description of my case, which seem to have possibly caused a bit of confusion.

In the case I described earlier in this issue, the URLs are supposed to contain the language string, ex. "/en/".
The problem occurs if I have a link in ex. a "Custom HTML" module which links to an address without the language code included.
Upon clicking said link, it will then redirect me to the default language, rather than the language stored in the cookie.
In the previous version, the Joomla would detect the lack of language segment, then search the cookie for the current language, rather than simply throw you back to the default.

If this is the new expected behavior, then I find that quite bothersome, since it's a "feature" that we have been taking advantage of in pretty much all our projects.

Either way, I hope that clearifies things a bit.
Other than that, it's good to see so many people actively working figuring out the problem.
Keep up the good work everyone!

**Comment by HermanPeeren** [comment]
Main lesson: better, more systematically testing before commiting. 

I think we only have some edge cases left now. Unfortunately today I have to work first, but hope to finish my PR tonight. Hannes' #5140 was a very good and necessary step in cleaning up the code-mess in the original languagefilter-plugin, that might have worked but was unmaintainable. 

Don't know the cause of the other, menu-item-alias issue, so don't know for sure if it is related to the languagefilter-plugin. Until then, it is a seperate issue, even if it is *possibly* related. Just reverting a possibly related PR could cause other issues, so I would not recommend that.

**Comment by Hackwar** [comment]
The menu alias is fixed with #6254 

Regarding issues with language: There is quite a bit more cruft in JApplicationSite::initialiseApp(). Most of those checks there are unnecessary and quite a bit of those checks never evaluate to true. If the project is interested in cleaning up old code, that would be the next area to work on to improve the language system.

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/6254 does not solve the menu item alias here, or, rather, introduces other error. See PR.

**Comment by infograf768** [comment]
New https://github.com/joomla/joomla-cms/pull/6254 and https://github.com/joomla/joomla-cms/pull/6278 solve Falang, Virtuemart and menu item alias issues.

Just remains to solve this cookie one to be fine for 3.4.1

**Comment by Bakual** [comment]
Hannes did another attemp of solving this. Can you guys please test https://github.com/joomla/joomla-cms/issues/6371?

**Comment by rdeutz** [comment]
Problem fixed with #6452 so closing this one
