### ISSUE TITLE
Bug in Joomla 3.4x Tags do not display under article text with below/split setting.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#6624]
Hi,
There seems to be a bug in Joomla 3.4x for Tags in Articles for Menu Items that display Categories of articles and not just Single Article menu items. This bug is an issue in both my site template and the Joomla Protostar template.
In Article Manager global settings I used the "Position of Article info" setting under the Options tab. I attached a screenshot.
When I have it set to "Above", the Tags do display correctly below the article title and above the article text.
But when I set it to "Below" or "Split", the Tags do NOT display at all anywhere on the article page.
You can see my thread on the Joomla forum about this issue: http://forum.joomla.org/viewtopic.php?f=706&t=881148

I had posted this as part of another Tags issue but that was already closed so I'm creating this new issue. https://github.com/joomla/joomla-cms/pull/6507#issuecomment-88063482
.
![2015-03-31 article manager position info setting](https://cloud.githubusercontent.com/assets/9383382/6927384/11cebae6-d7bb-11e4-83aa-4efc72eda98c.JPG)

**Comment by bertmert** [comment]
Article Manager Options > Articles:
There's a global option show_tags.
The same setting in menu items for Blog and Featured.

Category-Blog-View:
If show_tags is set to YES: In Category-Blog-View tags are shown ALWAYS below headline. "Position of Article Info" is ignored completely in blog view.
So, I don't understand why you don't see the tags anymore when changing "Position of Article Info".

Featured-View:
In Featured-View tags never were displayed. That's a bug.
PR https://github.com/joomla/joomla-cms/pull/6625 only displays tags now if  "Position of Article Info" is set to BELOW or SPLIT but doesn't show them with ABOVE.

Single Article:
When I go to a Single Article View changing global setting "Position of Article Info" works correctly.

Which bahavior is expected one?????

**Comment by bertmert** [comment]
@nemmar I think all is solved now? Sorry for confusion. I've corrected my last comment now.

**Comment by wilsonge** [comment]
We've fixed this in our development branch - tags now display beneath the article. Thanks for reporting this!!PHP Town Hall

**Comment by TheWizl** [comment]
This still doesn´t working for me. Is this bug-fix not committed to official Joomla 3.4.3?
Does this issue need a new ticket?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6624">issues.joomla.org/joomla-cms/6624</a>.</sub>

**Comment by wilsonge** [comment]
This should have been shipped in 3.4.2 - if it isn't looking fixed to you then can you open a new ticket with steps to reproduce the issue please :)

**Comment by krogias** [comment]
I have the same issue with 3.8.1. Tags are shown only in "above" option.

**Comment by brianteeman** [comment]
@krogias please do not comment on a 2 year old issue - no one will see it. Please create a new issue and reference this one if you wish
