### ISSUE TITLE
extension update - custom message from script.php missing since Joomla 3.4.0

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#6652]
#### Steps to reproduce the issue
Install plgSpambotCheck_j3.0.0_1.3.12.zip through extension manager an Joomla! 3.4.x installation (which you can download from our Joomla! extensions download menu http://www.vi-solutions.de/en/downloads-spambotcheck/joomla-extension-plugin-spambotcheck-1-3-12)
Go to Menu "Update" in extension manager
Click "Find Updates", you will see an update for the Plugin in the list then
Check the update and click "Update"

#### Expected result
Display of custom installation message (see ![screen shot 2015-04-03 at 13 26 40](http://issues.joomla.org/uploads/1/769a59e316251f18b55007f4b8e3da50.jpg))

#### Actual result
Message is missing. See ![screen shot 2015-04-03 at 13 27 31](http://issues.joomla.org/uploads/1/a5361454353cfe01c2d0832c30f17dfe.jpg)

#### System information (as much as possible)
Tested on
Joomla! 3.4.0 or 3.4.1
php 5.4.7, 5.4.21 on XAMPP and php 5.3.29 on productive Linux server

#### Additional comments
The userState, that contains the message, is cleared in the model administrator/components/com_installer/models/update.php function populateState
$app->setUserState('com_installer.message', '');
$app->setUserState('com_installer.extension_message', '');
As this function is called more than once during the update on the second call the message ist always ''.
Actually I have never seen a Joomla! extension before, that clears the userState in the model and I think this is the wrong place.

**Comment by brianteeman** [comment]
Please retest with the current staging release as it looks to me that the problem has been fixed elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6652">issues.joomla.org/joomla-cms/6652</a>.</sub>

**Comment by avjoomla** [comment]
Hi,
I retested with the current staging release (right after your made the comment) but sadly the problem still exists in the same way. I have tested with Joomla! 3.4.3 as well. But nothing's changed.

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6652">issues.joomla.org/joomla-cms/6652</a>.</sub>
