### ISSUE TITLE
Definetively resolve single tag redirect on multilanguage site

### ISSUE THREAD

**Issue by queengab** [joomla/joomla-cms#6687]
Hi to all,

i would like to point out for the last time the problem with joomla and single tag page.
I saw around the web some solutions but there isn't a definitive solution.
On joomla 3.3.6 i bypass it but now (i'm using 3.4.0) i can reproduce the error in the same way and i'd like to find a solution to update definetely.
I used a clean 3.4.0 version for this site. No updating, no migration.

I create a menu item inside a hidden menu that list all of my tags with precise language (italian in this case) and created two tags inside an article. 

I can view the main page of tags 
(index.php?option=com_tags&view=tags&tag_list_language_filter=it-IT&lang=ita)
that show me tha actual tag. 
If i click the single tag i have a 1054 error and the url is the following:
(index.php?option=com_tags&view=tag&id=2-articletitle&lang=ita)

If i enable sef url the single tag have this url (ita/component/tags/tag/2-articletitle.html) but is redirected to (ita/tags/2-articletitle)

if instead i use this url (ita/tag/tags/2-articletitle)that is the right seo url! ... the cms redirect to index.

I didn't find anything about this issue.
Is there someone who can help me? 

I dont' know if the problem is related to language or about the assignement of tamplate.

I tried to use the file components/com_tags/helpers/route.php on hackwar branch, nut nothing happens...

Thanks very much
Gabriele

**Comment by queengab** [comment]
Update to joomla 3.4.1 but nothing happens

**Comment by carmeloMagna** [comment]
Hi Gab,
What you discovered it's just one of the funny-funny bugs core joomla has in routings links.
I resolved the problem in that way, but I doutb it's "definitively" solved. It's just a work around.

In file /com_tags/router.php

go to line 148 and comment the line, than replace next lines as following:

**Comment by queengab** [comment]
Oh yeah! Works like a charm!
Thnak you very much!!! 

I hope this is a good solution but we need a function that can handle this problem definetely.
I don't know if someone of the joomla development staff is working on this issue on joomla future versions.

We will waiting for response, but thanks very much for the moment! You have saved a lot of time to hundreds people! 

Bye
Gabriele

**Comment by bertmert** [comment]
> I don't know if someone of the joomla development staff is working on this issue on joomla future versions.

I think it's @Hackwar

**Comment by infograf768** [comment]
@carmeloMagna
can you make a PR?

**Comment by Hackwar** [comment]
That is not a solution to the underlying problem and will not work for everybody. I have looked into this issue and it is not fun to get this to work correctly, especially since several people expect the tagging to do several different things, which the current solution all fullfills, but only half way. Anyway, I will try to look into this for 3.5. I wont introduce this in 3.4.x

**Comment by carmeloMagna** [comment]
Hello everybody,

and thank you for your reply. I well understand that mine it's not a solution.

I posted here because for the specific problem @queengab the hack works. Obviously the routing file is not so "pure" as everibody expect. Indeed, the page redirection goes to /ita/tags/mytag.html and not to /ita/tags/tag/mytag.html... in my simple site the solution is good enought to avoid any "404" or blanck page, but, of course, fix the code is not so "fun", as @Hackwar already said.

Yesterday I also noted that if you want to show the tag title in page /ita/tags/mytag.html you also find a duplicated title (ie. mytag mytag)

The problem is in file /components/com_tags/views/tag/view.html.php in the function getTagsTitle() @line 290

I fixed it with this (very stupid!!) control:
		```if(count($tags_title) > 1 && $tags_title[0] == $tags_title[1] ){
			return $tags_title[1];
		}else{
			return implode(' ', $tags_title);
		}```

So, my intent is just to focus into the problem, hope I could be usefull in some manner.

Thank you

CM

**Comment by brianteeman** [comment]
@hackwar did you address this in your router rewrite or is it still to be worked on?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/joomla-cms/6687</a>.</sub>

**Comment by brianteeman** [comment]
@hackwar any comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/joomla-cms/6687</a>.</sub>

**Comment by Hackwar** [comment]
I did not work on the tags component

**Comment by queengab** [comment]
Hi to all,

after 3 years i post again on this topic.
Recently i updated my joomla version to 3.8.6 fopr two websites.

Well i have gain the same problem with tag routing:

**With sef enabled**
https://www.mysite.it/it/component/tags/tag/mytag.html redirect to
https://www.mysite.it/it/tags/35-mytag

_Have a generic error with browser_ 

"This page is not redirected to the topic
Firefox has detected that the server is redirecting the request for this page so that it can never be satisfied.
This problem is often caused by blocking or refusing cookies."

**With sef disabled**
http://www.mysite.it/index.php?option=com_tags&view=tag&id=1049:my-tag-blabla&lang=it redirect to
http://www.mysite.it/index.php?lang=it

_No error but redirect to home page_

What happens?
Tried to change the file `/components/com_tags/router.php` following [https://github.com/joomla/joomla-cms/pull/18407](url), but nothing!

Bye

**Comment by roland-d** [comment]
@Hackwar I want to call you one more time, is this something that should be fixed with the new router or is it unrelated?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by ghost** [comment]
@roland-d as i understand @Hackwar 's Comment above "I did not work on the tags component" its unrelated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by ghost** [comment]
Issue confirmed.

After you create a menuitem for the tag you still get /component/tags/tag/tag-name when you click on article and scrool down to the tag.

What are your steps to reproduce /tags/tagname instead of /component/tags/tag/tag-name ?

**Comment by danham567** [comment]
(index.php?option=com_tags&view=tags&tag_list_language_filter=it-IT&lang=ita)
that show me tha actual tag.
If i click the single tag i have a 1054 error and the url is the following:
(index.php?option=com_tags&view=tag&id=2-articletitle&lang=ita)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by danham567** [comment]
[113.pdf](https://issues.joomla.org/uploads/1/de2e58e6fee5a3c4ff69cadf0a133969.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig please delete the spam and block the user

**Comment by ghost** [comment]
~~can't block user, please do one have the privilieges.~~
done

**Comment by ghost** [comment]
Hi to all, @roland-d @carmeloMagna @queengab 

after 5 years post again on this topic.
Recently i updated my joomla version to 3.9.15

Well the same problem with tag routing

**Comment by dunkmark** [comment]
Thanks For Information....



https://issues.joomla.org/uploads/1/51ab7d3d477828a67373b447ac7de2d7.docx
https://issues.joomla.org/uploads/1/813e9a31386348439fa3a872f82bd0a0.docx
https://issues.joomla.org/uploads/1/dbd1327cabaaf0361df6c9ddf3b9a443.docx
https://issues.joomla.org/uploads/1/858011b6a8307378e6fe86b1816e2c66.docx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by LucasBenjamin112** [comment]
[6 Essay Writing Tips to Help You Write Better.pdf](https://issues.joomla.org/uploads/1/998d2c0c3f148622015ced09bd0cd90c.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by LucasBenjamin112** [comment]
[Different Types of Essays.pdf](https://issues.joomla.org/uploads/1/f309a09f4748c15de1c276309e6f50c9.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by LucasBenjamin112** [comment]
[Writing a Psychology Essay.pdf](https://issues.joomla.org/uploads/1/d435cd4bdfa431737737bee8a1de4fd6.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by LucasBenjamin112** [comment]
[How to Begin Your Essay Successfully.pdf](https://issues.joomla.org/uploads/1/eda022699718361a385d2ca7b68e32df.pdf)[How to Format a Thesis Proposal.pdf](https://issues.joomla.org/uploads/1/9a424cf8e21f67afa5855d89477df2b2.pdf)[Sorts of Public Speeches.pdf](https://issues.joomla.org/uploads/1/1f6967c370228cbfcfbbeabe423d3c03.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6687">issues.joomla.org/tracker/joomla-cms/6687</a>.</sub>

**Comment by brianteeman** [comment]
Please block and remove these posts AND dont forget to delete the files from the issue tracker server

**Comment by zero-24** [comment]
Deleted the posts and requested to delete the files too. Thanks.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have spent quite some time today reviewing this in Joomla 4 and as this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)

**Comment by Hackwar** [comment]
This is still a valid issue. We still need to fix this in 4.x

**Comment by brianteeman** [comment]
@Hackwar are you sure? I was unable to replicate the reported problem. I didnt just blindly close it

**Comment by Hackwar** [comment]
I just looked at the 4.2-dev branch and the tags router there is still the same crap it has been since Joomla 3.2. It is broken in loads of places and still needs a complete rewrite. To be honest, it is such a clusterfuck that I'm pushing that away for years now. Mea culpa. I swear, I'll get to that before 4.4 is released.

**Comment by brianteeman** [comment]
Maybe I did something different which is why I couldnt replicate it?


https://user-images.githubusercontent.com/1296369/186915882-929c330b-761c-4ae3-ade4-222f69c5b2d6.mp4

**Comment by Hackwar** [comment]
#39140 should fix this, so I'm closing this one.
