### ISSUE TITLE
Weblinks image

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#7888]
#### Steps to reproduce the issue
Install the Weblinks package into Joomla
Create a new weblink
In the images select an image
Save
Message says saved but image field shows empty

#### Expected result
Image field should show the image link that was selected

#### Actual result
Message says saved but image field shows empty

#### System information (as much as possible)
Windows 10 but sys info says 8
>PHP Built On 	Windows NT MY-COMPUTER 6.2 build 9200 (Windows 8 Home Premium Edition) i586
Database Version 	5.6.26
Database Collation 	utf8_general_ci
PHP Version 	5.5.28
Web Server 	Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.5.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.5 Development [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by Bakual** [comment]
Please open the issue in the weblinks repo. It's not part of the core anymore.
https://github.com/joomla-extensions/weblinks

**Comment by Bakual** [comment]
That being said, it sounds like it's already fixed with https://github.com/joomla-extensions/weblinks/pull/91

**Comment by Webdongle** [comment]
Nope not fixed that is not the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7888">issues.joomla.org/joomla-cms/7888</a>.</sub>

**Comment by Bakual** [comment]
> You can save, but images are not saved: if you edit, all fields remains empty.

Sounds very similar to 

> Message says saved but image field shows empty

**Comment by Webdongle** [comment]
But it was merged 5 days ago and is about 2 image tabs.  I installed the weblinks component an hour ago

set up tracker https://github.com/joomla-extensions/weblinks/issues/93

**Comment by brianteeman** [comment]
Just because it was merged does NOT mean it has been released

On 15 September 2015 at 13:12, Webdongle <notifications@github.com> wrote:

> But it was merged 5 days ago and is about 2 image tabs. I installed the
> weblinks component an hour ago
>
> set up tracker joomla-extensions/weblinks#93
> <https://github.com/joomla-extensions/weblinks/issues/93>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7888#issuecomment-140369668>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Webdongle** [comment]
Good point ... I used com_weblinks from the zip from https://github.com/joomla-extensions/weblinks ... it works now.

Thanks

**Comment by mailtomayaz** [comment]
Just add on top of /administrator/components/com_weblinks/views/weblink/tmpl/edit.php
$this->ignore_fieldsets = array('images');
