### ISSUE TITLE
Invalid DOB on user registration results in 500 error upon redirect, instead of successful redirect and display of validation error

### ISSUE THREAD

**Issue by Ry-Fi** [joomla/joomla-cms#8093]
#### Steps to reproduce the issue

- Require Date of Birth (DOB) on User Profile
- Attempt to Register a user using an invalid date for the DOB - ex: **1970-13-13**

#### Expected result

- Registration will fail, redirecting back to the registration form and showing the DOB validation error **"Registration failed: The date of birth you entered is invalid. Please enter valid date."** (PLG_USER_PROFILE_ERROR_INVALID_DOB)

#### Actual result

- Instead, the redirect fails on the invalid date, resulting in a **500 error** page showing **"DateTime::__construct(): Failed to parse time string (1970-13-13) at position 6 (3): Unexpected character"**

#### System information (as much as possible)

- PHP 5.5.0RC3
- MySQL 5.5.32

#### Additional comments

- Should be trivial for someone else to try to reproduce and confirm or deny

**Comment by zero-24** [comment]
Please try https://github.com/joomla/joomla-cms/pull/7849 it should fix the issue with the next update to 3.4.5

**Comment by Ry-Fi** [comment]
Unfortunately that didn't fix it for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8093">issues.joomla.org/joomla-cms/8093</a>.</sub>

**Comment by infograf768** [comment]
I confirm the issue on staging

**Comment by Ry-Fi** [comment]
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8093">issues.joomla.org/joomla-cms/8093</a>.</sub>

**Comment by ggppdk** [comment]
Actually this is 2 bugs, and both can effect other code and 3rd party extensions

- Uncaught exception in filtering code
- Uncaught exception after form reload if form validation fails (e.g. email exists)

Filtering types for  'SERVER_UTC'  'USER_UTC'
do not use try-catch, in
>libraries\joomla\form\form.php


```
// Return an SQL formatted datetime string in UTC.
$return = JFactory::getDate($value, $offset)->toSql();
```

should (probably) be
```
// Return an SQL formatted datetime string in UTC.
try {
	$return = JFactory::getDate($value, $offset)->toSql();
} catch (Exception $e) {
	$return = '';
}
```

Similar the getInput() of calendar field (dob element extends calendar element)
on form-reload after validation will be given to display the invalid date that was posted
>libraries\joomla\form\fields\calendar.php
```
// Get a date object based on the correct timezone.
$date = JFactory::getDate($this->value, 'UTC');
```
should (probably) be
```
// Get a date object based on the correct timezone.
try {
	$date = JFactory::getDate($this->value, 'UTC');
} catch (Exception $e) {
	$date = JFactory::getDate();
}
```

i can not do a pull request now,
but anyone else can do and also confirm fix,
and do whatever more is needed

**Comment by ggppdk** [comment]
and each of the above is needed in 2 places, (for both 'SERVER_UTC'  and  'USER_UTC')

**Comment by Ry-Fi** [comment]
Thanks for your assessment of this issue.

Now forgive me, I'm not a Joomla contributor, just some schmoe trying to use it... but I've implemented the changes you're suggesting into my development work and this doesn't seem like the correct solution to me.  Instead of resulting in the expected _validation error_, **"Registration failed: The date of birth you entered is invalid. Please enter valid date."**, this is instead resulting in a _simple warning_, **"Field required: Date of Birth:"**, and resetting the entered date to today's date, which obfuscates the issue being that the user entered an invalid date.   Therefore this doesn't really accomplish the correct fix that would be consistent with Joomla, in my opinion.

I will admit that I'm not very familiar with the form validation architecture to have any better idea of how this should be addressed, so I'm not really helpful in knowing what the correct solution would be... but surely the ideal fix is obvious to someone who's well-versed in this part of the system, no?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8093">issues.joomla.org/joomla-cms/8093</a>.</sub>

**Comment by ggppdk** [comment]
That is not relevant to my suggested fix. 
The fix is needed,

- what extra work the DOB field needs to do afterwards it is up to the field itself

e.g. in our case the DOB field can see that 
- a non-empty value was converted by date validation to empty,
thus set a message for invalid value, instead of empty value

again that is extra code, that needs to be done extra to the suggested fix

**Comment by ggppdk** [comment]
I am not sure where that code should be, 
because i have not looked at it more,

maybe it is not inside the code of the field, maybe inside the JForm class

**Comment by infograf768** [comment]
Maybe the Exception could also throw an enqueueMessage?

**Comment by ggppdk** [comment]
Yes, that sounds like a good option

- invalid date date when filtering code for types 'SERVER_UTC' 'USER_UTC', inside
libraries\joomla\form\form.php

should set both
- set $return to empty and also enqueue a warning

Just the user will get 2 messages:
- invalid date by the filtering code
- required field is empty, by the validating code (because filtering set it to empty)

but actually that is another issue the message of validating code:
- for required fields it set a misleading message, if filtering sets a form value to empty string

**Comment by ggppdk** [comment]
Similar issue: #8646

**Comment by brianteeman** [comment]
Please see and test #8656 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8093">issues.joomla.org/joomla-cms/8093</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8093">issues.joomla.org/joomla-cms/8093</a>.</sub>

**Comment by JasonCromer** [comment]
Looks like this is happening again, on MacOSX.
