### ISSUE TITLE
Possible bug to display expanded Sub-Categories frontend menu item.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#8437]
To display expanded Sub-Categories frontend menu item.
The issue and possible bug can be found posted on the Joomla forum:
http://forum.joomla.org/viewtopic.php?f=706&t=899170

Update: I had posted this bug as an issue on Github about a year ago but I cannot find the link to that post in my account. There were some Joomla devs working on this issue but I don't think it's finished since the problem still occurs in the latest version of Joomla.

**Comment by brianteeman** [comment]
@nemmar I believe your previous issue was #4937 which was fixed with #5469

Are you still having an issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8437">issues.joomla.org/joomla-cms/8437</a>.</sub>

**Comment by nemmar** [comment]
Hi Brian,

Yes, I am still having this issue on my Joomla sites. My sites are Joomla! 3.4.8 Stable and I have PHP 5.5 on my server. I will be upgrading to PHP 7 when Joomla 3.5 stable is released. Do you think that will fix this?

You can see that the sub-level categories do not open when you click the menu items even though I have the Article Global Settings set to open all sub-category levels. On my sites I have to click the small white dash-tab icon on the right side of the main category on the page to display the sub-category levels. Here is an page URL and I have attached 3 screenshots of my backend settings.
http://www.nemmar.com/real-estate-library

![2016-03-18 global show all sub-cats articles setting](https://cloud.githubusercontent.com/assets/9383382/13893482/1be2fa3e-ed35-11e5-8091-7273b6061352.JPG)
![2016-03-18 menu item global show all sub-cats setting 1](https://cloud.githubusercontent.com/assets/9383382/13893484/1be4e3bc-ed35-11e5-9675-ece35e379302.JPG)
![2016-03-18 menu item global show all sub-cats setting 2](https://cloud.githubusercontent.com/assets/9383382/13893483/1be40050-ed35-11e5-8111-98f98a90070f.JPG)

**Comment by andrepereiradasilva** [comment]
i can't reproduce this on latest staging

**Comment by pintobuck** [comment]
This is a work around that worked for me on Joomla 3.6
http://forum.joomla.org/viewtopic.php?f=706&t=899170&p=3416002#p3416002

Also, here is some code that might work.  I'm not a programmer, so I'll leave the evaluation to you.

https://www.beginwithb.com/begin-with-b/blog/subcategories-title-in-category-or-blog-view-with-multiple-columns-in-joomla

https://www.youtube.com/watch?v=LmrIr0fUXSw

**Comment by franz-wohlkoenig** [comment]
@nemmar  at http://www.nemmar.com/real-estate-library SubCat. works, so i guess thie Issue is solved?

**Comment by nemmar** [comment]
The sub-categories can be expanded by clicking the + symbol. But Joomla still does not display the sub-categories already expanded when you view the categories pages even if you have the configs set to display all sub-cats. So it seems to me that it's not fixed but if the plus sign is the only option, then that's what I'll have to leave it with. It would be better if the sub-cats could be displayed as expanded on pageview.

**Comment by franz-wohlkoenig** [comment]
Try to understand: On your Site is 

- Cat. "Nemmar Real Estate Training Top-Rated Books and DVD Videos"
- SubCat. "Energy Saving Home Improvements from A to Z"

Click on SubCat. opens Menu for SubCat. Where should SubCats shown?

**Comment by nemmar** [comment]
Hi,

The link to my online real estate library that you posted has the example of what I'm referring to.
https://www.nemmar.com/real-estate-library
Screenshot: https://drive.google.com/file/d/0BwXZzY2mIiORUkJCLVZKdE96dk0/view?usp=sharing

If you click any of the + icons next to the main categories, you will see them open to display the sub-categories. Some of the main categories have multiple sub-category levels.

**Comment by franz-wohlkoenig** [comment]
So you want the +-Sign gone and all SubCat. are shown - got it?

**Comment by nemmar** [comment]
Hi,

You can still have the + sign display next to the categories and sub-categories, but just have the Global configs settings match the expanded or collapsed view of the sub-cats. For example, the plus sign is useful to expand/collapse the cats/sub-cats while users view the page. But if possible have Joomla function like it used to with the config setting of expanded or collapsed display of the sub-categories on pageview. That way if a Joomla site admin wants to display either view, they just have to set the configs to what they want, instead of the site visitor having to know they need to use the + signs to change views.

**Comment by franz-wohlkoenig** [comment]
@nemmar i don't really get you Scenario, so calling others to discuss this issue to move forward.

**Comment by nemmar** [comment]
Hi,

Screenshot: https://drive.google.com/file/d/0BwXZzY2mIiORa3pkei1qNTV3N2c/view?usp=sharing

As the site admin, in the backend, if you go to Articles > Options > Category. There is an config setting to choose how you want to display the sub-categories on a page. If you select "All" then Joomla should display all the sub-categories expanded, or at least that is how it used to work before this bug/change occurred. 

So what I'm saying is it's fine to also have the + sign next to the categories and sub-categories even if the sub-categories config is set to display "All". That way if a site has many sub-categories for the articles, like mine does, then a site user/visitor who is viewing that page can click the + sign (if they're not a novice and know what it's for) to collapse/expand the cats/sub-cats if they want to change the view.

**Comment by Schmidie64** [comment]
@icampus
I also could reproduce this item, but I think there is no need to fix it.  Its more clearer to let it how it is. For example if you have a Website with a few hundred Sub-Categorys its not clear whitch Sub-Category belongs to a Category.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8437">issues.joomla.org/tracker/joomla-cms/8437</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th October 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.
