### ISSUE TITLE
Smart Search - search suggestion does not obey access permission of content

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#8655]
#### Steps to reproduce the issue
Backend: Create a new article with access "Registered" and type "THIS IS SECRET".
Frontend: without being logged in, in smart search start typing "THI.."

#### Expected result
No suggestion is shown since the sentence is not accessible to unlogged users

#### Actual result
Smart search shows up "THIS IS SECRET" as a suggestion, while it should not since the content access is just for registered users. Infact, if you type "THIS IS SECRET" in the search box and hit "search", it will not find no occurrence, since the content is not visible to public/guests.

#### System information (as much as possible)
Joomla 3.4.5 on Windows XAMPP

**Comment by ggppdk** [comment]
I think this is a known limitation of the implementation for word completing (suggestions),
which gives fast server response but does not take into account things

- such as access and other, thus all content is added to the term index

you can see relevant comments of @chrisdavenport , here:
#8309 

I think a new label is needed to mark such issues calling it ?:
"Known limitation"

**Comment by chrisdavenport** [comment]
See also: https://issues.joomla.org/tracker/joomla-cms/4401<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8655">issues.joomla.org/joomla-cms/8655</a>.</sub>

**Comment by tomartailored** [comment]
i have tested it works properly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8655">issues.joomla.org/joomla-cms/8655</a>.</sub>

**Comment by brianteeman** [comment]
Closing as this can no longer b replicated. It must have been fixed elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8655">issues.joomla.org/joomla-cms/8655</a>.</sub>

**Comment by Giuse69** [comment]
It is NOT fixed, the test of tomartailored probably is not correct. I tested also on Joomla 3.6.2 and I am still getting suggestions of words in articles with access limited to registered - NB I refer to suggestions, not to search results that work fine, infact the user receive a suggestion while typing as the word/sentence do exist, then press Enter and no result.
This bug / lack of filter is against privacy/security since it shows restricted content.

**Comment by brianteeman** [comment]
I tested this myself with Joomla 3.6.2, following your instructions and could not replicate

**Comment by chrisdavenport** [comment]
This is a known issue and has been since before the first release.  It is documented that anyone who wants words from restricted articles to not be shown in the autocompletion should not use autocompletion.

A PR to fix the issue would be welcome, however a general fix is unlikely to be simple (which is probably why nobody has come up with a PR so far).

**Comment by Giuse69** [comment]
Ok, so che problem is confirmed (probably Brian hasn't tested the autocomplete feature that I was making as "suggestions as you type") :).
Since it's hard to overcome now but I think it's a serious hole in security (you think of hiding information and the autocompleter even suggests you the following words :) ), at least I would add a warning / tooltip when enabling autocomplete that warns about this. Can be done?

**Comment by Giuse69** [comment]
Language filter is respected, access level not, I think it should be noticed in backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8655">issues.joomla.org/joomla-cms/8655</a>.</sub>
